In [ ]:
## MAKE NOTES ABOUT KNOWLEDGE BASE. 
# SPECIFICALLY IF I PROCESS NOT GENERAL DEFINITION IT WILL BE BROUGHT OVER. 
# General Definition it will only include if already Included

In [ ]:
# Change the Length of the Columns in the Dashboard.
# Filtering Order for Processes and Categorization is not great for anything that isn't a Formal PRocess with Process steps.
# Should be able to add an additional layer, so when there is #NA in orignal columns it still works.

#  Build a process for Specific Types of ML Procesess, Clustering to incorporate additional features into process - Convoluted as normal step.

In [1]:
import pandas as pd
import numpy as np
import sys

sys.path.append("/Users/derekdewald/Documents/Python/Github_Repo/d_py_functions")

In [2]:
from daily_etl_folder_mgmt import generate_files_for_streamlit

knowledge_base_df= generate_files_for_streamlit()

In [4]:
knowledge_base_df[knowledge_base_df['Process']=='Story Telling']

,Process,Categorization,Word,Definition,Source
650,Story Telling,Process Step,Define Story,What you want people to take away and feel,Knowledge Base
651,Story Telling,Process Step,Define the Armature,"The armature is the core message, moral, or tr...",Knowledge Base
652,Story Telling,Process Step,Define your Plot,Series of events which transpire. \nData Scien...,Knowledge Base
653,Story Telling,Process Step,Identify your Theme,"Trying for theme is important, but you won't s...",Knowledge Base
654,Story Telling,Process Step,Identify your Theme,"Trying for theme is important, but you won't s...",Knowledge Base
655,Story Telling,Process Step,Identify your Characters,You admire a character for trying more than fo...,Knowledge Base
656,Story Telling,Process Step,Define your Call to Action,What specifically are you asking? How will you...,Knowledge Base
657,Story Telling,Process Step,End First.,Come up with your ending before you figure out...,Knowledge Base
658,Story Telling,Consideration,End First.,Come up with your ending before you figure out...,Knowledge Base
659,Story Telling,Consideration,Don't Fall In Love with Your Story,"You can't fall in love with the story, or you ...",Knowledge Base
660,Story Telling,Consideration,Don't confuse your theme,Competition is not a theme. Competition is a n...,Knowledge Base
661,Story Telling,Consideration,Challenge your Character,What is your character good at; comfortable wi...,Knowledge Base
662,Story Telling,Consideration,Be Authentic,You have to identify with your situation/chara...,Knowledge Base
663,Story Telling,Consideration,Be Authentic,You have to identify with your situation/chara...,Knowledge Base
664,Story Telling,Consideration,Do not chase Perfection,Finish your story; let go of it even if it's n...,Knowledge Base
665,Story Telling,Consideration,Getting Unstuck,"When you're stuck, make a list of what wouldn'...",Knowledge Base
666,Story Telling,Consideration,Learn from Good Examples,Pull apart the stories you like. What you like...,Knowledge Base
667,Story Telling,Consideration,Just do it.,Putting it on paper lets you start fixing it. ...,Knowledge Base
668,Story Telling,Consideration,Challenge yourself.,"Discount the first thing that comes to mind, a...",Knowledge Base
669,Story Telling,Consideration,Don't make it simple,Give your characters opinions. Passive/malleab...,Knowledge Base
670,Story Telling,Consideration,Understand your motivation,Why must you tell this story? What's the belie...,Knowledge Base
671,Story Telling,Consideration,How would you feel?,"If you were your character, in this situation,...",Knowledge Base
672,Story Telling,Consideration,Stakes Matter.,What are the stakes? Give us reason to root fo...,Knowledge Base
673,Story Telling,Consideration,Nothing is Wasted,"No work is ever wasted. If it's not working, l...",Knowledge Base
674,Story Telling,Consideration,Don't knickpick,You have to know yourself and know the differe...,Knowledge Base
675,Story Telling,Consideration,Don't Cheat.,Coincidences to get characters into trouble ar...,Knowledge Base
676,Story Telling,Consideration,Learn from Bad Examples,Take the building blocks of a movie you dislik...,Knowledge Base
677,Story Telling,Consideration,Ethos – Character,You are the character in your story. You need ...,Knowledge Base
678,Story Telling,Consideration,Logos – Reason,Articulate why your audience should care,Knowledge Base
679,Story Telling,Consideration,Pathos – Emotion,"Tell stories, make people feel it.",Knowledge Base
680,Story Telling,Consideration,Metaphor,"Can help people understand. Need to take care,...",Knowledge Base
681,Story Telling,Consideration,Logic Not a Message,The logic of discovery is not the logic of pre...,Knowledge Base

In [4]:
knowledge_base_df

,Process,Categorization,Word,Definition
0,Goal Setting,Process,Definition,"Thought process utilized to establish a clear,..."
1,Problem Definition,Process,Definition,"A Clear, Concise and explicit definition of th..."
2,Data Collection,Process,Definition,"Data collection involves identifying, sourcing..."
3,Data Preparation,Process,Definition,Data preparation focuses on cleaning and struc...
4,Exploratory Data Analysis,Process,Definition,Foundational step in ensuring the success of a...
...,...,...,...,...
246,Understand Your Audience,Process Step,What do they want?,The more we know about the motivations and inc...
247,Understand Your Audience,Process Step,Are they likely to Care?,
248,Understand Your Audience,Example,Getting CEO to Pick,How to get a CEO to remove a soft drink from J...
249,Understand Your Audience,Consideration,Stress Induced U Curve,High Pressure Decision Making: The inverted U ...
250,Understand Your Audience,Example,Cuban Missile Crisis,"Asymmetric Information, Deception, Misreading ..."

In [6]:
consolidated_df[consolidated_df['Process']=='']

    Process Categorization Word Definition
0
1
2
3
4
..      ...            ...  ...        ...
251
252
253
254
255

[264 rows x 4 columns]

In [4]:
consolidated_df[consolidated_df['Process']=='Communication']

,Process,Categorization,Word,Definition
35,Communication,Process,Definition,
36,Communication,Process Step,Understand Your Message,
37,Communication,Process Step,Understand Your Audience,
38,Communication,Process Step,Understand Your Strategy,"Beyond understanding Your Message, you need to..."
39,Communication,Process Step,Choosing a Medium,"While not always give a choice, it is importan..."
40,Communication,Process Step,Understand Your Visuals,
41,Communication,Process Step,Message Spareness,"Utilize a less is more approach, whether that ..."
42,Communication,Process Step,Re-enforce the Message,
43,Communication,Process Step,Cardinal Communication Sins,
44,Communication,Cardinal Communication Sins,Deliver Simplicity,Do not make the user think
45,Communication,Cardinal Communication Sins,Do Not Demand Recall,Do not make the user remember. If the Speaker ...
46,Communication,Cardinal Communication Sins,Visuals in 2D,Do not use 3D unless absolutely necessary.
47,Communication,Cardinal Communication Sins,Avoid Pie Charts,Pie Charts. They Suck.
48,Communication,Cardinal Communication Sins,Do Not Offend Your Audience,
49,Communication,Cardinal Communication Sins,Do Not Let Predjudices Close Your Mind,
50,Communication,Cardinal Communication Sins,Don’t waste the advantage that thought has ove...,
51,Communication,Cardinal Communication Sins,Hearing vs Listening,"Most were born hearing well, EVERYONE must lea..."
52,Communication,Cardinal Communication Sins,Always Thank Your Audience,
53,Communication,Process Step,General Expectations,
54,Communication,Process Step,Measuing Effectiveness,How can one measure how effective/ineffective ...

In [5]:
consolidated_df[consolidated_df['Process']=='Machine Learning Lifecycle']

,Process,Categorization,Word,Definition
104,Machine Learning Lifecycle,Process,Definition,To Be Defined
105,Machine Learning Lifecycle,Process Step,Goal Setting,"Thought process utilized to establish a clear,..."
106,Machine Learning Lifecycle,Goal Setting,Specific,Describes what will be accomplished and what s...
107,Machine Learning Lifecycle,Goal Setting,Measurable,Includes a clear way to track progress or dete...
108,Machine Learning Lifecycle,Goal Setting,Achievable,"Realistic given available time, resources, ski..."
...,...,...,...,...
192,Machine Learning Lifecycle,Monitoring,Clearly define production context windows,Define triggers for retraining or model review...
193,Machine Learning Lifecycle,Process Step,"Bias, Fairness, and Ethics",This step examines whether the model produces ...
194,Machine Learning Lifecycle,"Bias, Fairness, and Ethics",Review Demographics,Evaluate model performance across key demograp...
195,Machine Learning Lifecycle,"Bias, Fairness, and Ethics",Test unitended discrimination,Review sensitive features and proxy variables....
196,Machine Learning Lifecycle,"Bias, Fairness, and Ethics",Document Fairness Checks,Document fairness checks and mitigation steps....

In [3]:
#from daily_etl_folder_mgmt import ETL
#ETL()

python_function_list Saved to /Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/
python_function_parameters Saved to /Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/

In [3]:
from objects_automated import object_dict

links = pd.read_csv(object_dict['csv_links']['python_object']['d_links'])
notes = pd.read_csv(object_dict['csv_links']['python_object']['google_notes_csv'])
definitions = pd.read_csv(object_dict['csv_links']['python_object']['google_definition_csv'])
technical_notes = pd.read_csv(object_dict['csv_links']['python_object']['technical_notes'])

In [10]:
from daily_etl_folder_mgmt import extract_object_dot_py
from objects_automated import object_dict as object_dict_auto
from objects_manual import object_dict as object_dict_man

extract_object_dot_py(object_dict_man,'/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/object_manual_published.xlsx')
extract_object_dot_py(object_dict_auto,'/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/object_auto_published.xlsx')

In [3]:
from daily_etl_folder_mgmt import generate_objects_automated_py
generate_objects_automated_py()

In [10]:
consolidated_xlsx = '/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/consolidated_dataset.xlsx'
consolidated_df = pd.read_excel(consolidated_xlsx)

In [11]:
consolidated_df[consolidated_df['Process']=='Algorithm Classification']

,Process,Categorization,Word,Definition,Location
120,Algorithm Classification,Definition,Anomaly Detection,Algorithm which designed to identify observati...,Definitions
121,Algorithm Classification,Definition,Classification,Algorithm which assign observations to one of ...,Definitions
122,Algorithm Classification,Definition,Clustering,Algorithm which group observations into cluste...,Definitions
123,Algorithm Classification,Definition,Regression,Algorithm which predict continuous numerical v...,Definitions
124,Algorithm Classification,Definition,Ranking / Recommendation,Algorithm which order items or suggest relevan...,Definitions
125,Algorithm Classification,Definition,Density Estimation,Approaches which involve modeling the underlyi...,Definitions
126,Algorithm Classification,Definition,Dimensionality Reduction,Algorithm which reduce the number of variables...,Definitions
127,Algorithm Classification,Definition,Feature Selection,Methods that identify and retain a subset of e...,Definitions
128,Algorithm Classification,Definition,Feature Transformation,Methods which modify existing features into ne...,Definitions
129,Algorithm Classification,Definition,Information Retrieval,NaN,Definitions
130,Algorithm Classification,Definition,Time Series Forecasting,NaN,Definitions
131,Algorithm Classification,Definition,Generative Models,NaN,Definitions
132,Algorithm Classification,Definition,Reinforcement Learning,NaN,Definitions
133,Algorithm Classification,Definition,Optimization,NaN,Definitions
134,Algorithm Classification,Definition,Graph Algorithms,NaN,Definitions
135,Algorithm Classification,Definition,Prediction,NaN,Definitions

In [ ]:
from daily_processes import daily_test
daily_test()

In [ ]:
# Generate Python File Including All Dictionaries

from dict_processing import dict_defitions_dot_py
dict_defitions_dot_py()