In [1]:
import pandas as pd
import numpy as np
import sys

sys.path.append("/Users/derekdewald/Documents/Python/Github_Repo/d_py_functions")

In [4]:
from taxonomy_admin_functions import create_knowledge_base,create_python_documentation,generate_objects_automated_py
from objects_automated import object_dict

notes = pd.read_csv(object_dict['csv_links']['python_object']['google_notes_csv'])
definitions = pd.read_csv(object_dict['csv_links']['python_object']['google_definition_csv'])


knowledge_base_df= create_knowledge_base(
    definition_df=definitions,
    notes_df=notes
)

generate_objects_automated_py()

function_list,parameter_list,function_file_definition = create_python_documentation()

In [ ]:
## MAKE NOTES ABOUT KNOWLEDGE BASE. 
# SPECIFICALLY IF I PROCESS NOT GENERAL DEFINITION IT WILL BE BROUGHT OVER. 
# General Definition it will only include if already Included

In [ ]:
# Change the Length of the Columns in the Dashboard.
# Filtering Order for Processes and Categorization is not great for anything that isn't a Formal PRocess with Process steps.
# Should be able to add an additional layer, so when there is #NA in orignal columns it still works.

#  Build a process for Specific Types of ML Procesess, Clustering to incorporate additional features into process - Convoluted as normal step.

In [7]:
object_dict['csv_links']['python_object']['google_definition_csv']

'https://docs.google.com/spreadsheets/d/e/2PACX-1vQq1-3cTas8DCWBa2NKYhVFXpl8kLaFDohg0zMfNTAU_Fiw6aIFLWfA5zRem4eSaGPa7UiQvkz05loW/pub?output=csv'

In [9]:
from objects_automated import object_dict
from objects_manual import object_dict

object_dict['python_str_documentation']['python_object']

['Definition',
 'Parameters',
 'Returns',
 'Date Created',
 'Date Last Modified',
 'Process',
 'Categorization',
 'Usage',
 'Notes']

In [4]:
function_list.head()

,Function,Definition,Parameters,Returns,Date Created,Date Last Modified,Process,Categorization,Usage,Notes,Folder
0,univariate_analysis,NaN,"[df, sparsity_threshold, skew_threshold, extre...",NaN,None,None,None,None,NaN,None,eda_functions.py
1,ml_validation_data_cleaning,NaN,[df],NaN,None,None,None,None,NaN,None,eda_functions.py
2,visualize_dataframe_in_notebook,Function which applies some modest formating t...,"[df, show_as_number, show_as_currency, show_as...",Object Type date_created: 27-Aug-26 date_last_...,None,None,None,None,visualize_dataframe_in_notebook(df),None,eda_functions.py
0,InspectFunction,None,[function_name],None,None,None,None,None,None,None,utility_functions.py
0,read_directory,Function which reads reads a directory and ret...,"[location, file_type, match_str]",Dataframe,3-Dec-25,3-Dec-25,OS Folder Management,Directory Management,d_py_function = '/Users/derekdewald/Documents...,NaN,filesystem_tools.py

In [5]:
parameter_list.head()

,Function,Parameters,Type,Definition,Folder
0,univariate_analysis,df,,,eda_functions.py
1,univariate_analysis,sparsity_threshold,,,eda_functions.py
2,univariate_analysis,skew_threshold,,,eda_functions.py
3,univariate_analysis,extreme_threshold,,,eda_functions.py
4,univariate_analysis,high_cardinality_threshold,,,eda_functions.py

In [6]:
function_file_definition.head()

               Function                                         Definition
0      eda_functions.py                                               None
1  objects_automated.py                                               None
2  utility_functions.py                                               None
3   filesystem_tools.py  Function which stores all functions that deal ...
4     objects_manual.py                                               None