In [ ]:
## MAKE NOTES ABOUT KNOWLEDGE BASE. 
# SPECIFICALLY IF I PROCESS NOT GENERAL DEFINITION IT WILL BE BROUGHT OVER. 
# General Definition it will only include if already Included

In [1]:
import pandas as pd
import numpy as np
import sys

sys.path.append("/Users/derekdewald/Documents/Python/Github_Repo/d_py_functions")

In [2]:
from daily_etl_folder_mgmt import ETL
ETL()

python_function_list Saved to /Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/
python_function_parameters Saved to /Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/

In [5]:
from daily_etl_folder_mgmt import generate_knowledgebase

d = generate_knowledgebase()

In [10]:
from daily_etl_folder_mgmt import extract_object_dot_py
from objects_automated import object_dict as object_dict_auto
from objects_manual import object_dict as object_dict_man

extract_object_dot_py(object_dict_man,'/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/object_manual_published.xlsx')
extract_object_dot_py(object_dict_auto,'/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/object_auto_published.xlsx')

In [ ]:
from daily_etl_folder_mgmt import generate_objects_automated_py
generate_objects_automated_py()

In [10]:
consolidated_xlsx = '/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/consolidated_dataset.xlsx'
consolidated_df = pd.read_excel(consolidated_xlsx)

In [11]:
consolidated_df[consolidated_df['Process']=='Algorithm Classification']

,Process,Categorization,Word,Definition,Location
120,Algorithm Classification,Definition,Anomaly Detection,Algorithm which designed to identify observati...,Definitions
121,Algorithm Classification,Definition,Classification,Algorithm which assign observations to one of ...,Definitions
122,Algorithm Classification,Definition,Clustering,Algorithm which group observations into cluste...,Definitions
123,Algorithm Classification,Definition,Regression,Algorithm which predict continuous numerical v...,Definitions
124,Algorithm Classification,Definition,Ranking / Recommendation,Algorithm which order items or suggest relevan...,Definitions
125,Algorithm Classification,Definition,Density Estimation,Approaches which involve modeling the underlyi...,Definitions
126,Algorithm Classification,Definition,Dimensionality Reduction,Algorithm which reduce the number of variables...,Definitions
127,Algorithm Classification,Definition,Feature Selection,Methods that identify and retain a subset of e...,Definitions
128,Algorithm Classification,Definition,Feature Transformation,Methods which modify existing features into ne...,Definitions
129,Algorithm Classification,Definition,Information Retrieval,NaN,Definitions
130,Algorithm Classification,Definition,Time Series Forecasting,NaN,Definitions
131,Algorithm Classification,Definition,Generative Models,NaN,Definitions
132,Algorithm Classification,Definition,Reinforcement Learning,NaN,Definitions
133,Algorithm Classification,Definition,Optimization,NaN,Definitions
134,Algorithm Classification,Definition,Graph Algorithms,NaN,Definitions
135,Algorithm Classification,Definition,Prediction,NaN,Definitions

In [12]:




object_dict['algo_class_ref_list'] = {{
    'Process':"Algorithm Categorization",
    'Categorization':'Reference List',
    'Word':"Algorithm Categorization Reference List",
    'Definition':"Comprehensive List of all Values utilized in Algorithm Categorization",
    'publish':1,
    'python_object':{dot_py_proc}
    }}

In [ ]:
from daily_processes import daily_test
daily_test()

In [ ]:
# Generate Python File Including All Dictionaries

from dict_processing import dict_defitions_dot_py
dict_defitions_dot_py()

In [15]:
from objects_automated import object_dict

object_dictbba

{'cat_reference_list': {'Process': 'Dot Py String Taxonomy Categorization',
  'Categorization': 'Reference List',
  'Word': 'Dot Py String Taxonomy Categorization',
  'Definition': 'Comprehensive List of all Values utilized in Organizational Taxonomy in the Column Categorization',
  'publish': 1,
  'python_object': ['Directory Management',
   'File Management',
   'Excel File Creation',
   'Definition',
   'Manual File Creator']},
 'process_reference_list': {'Process': 'Documentation Taxonomy Categorization',
  'Categorization': 'Reference List',
  'Word': 'Documentation Taxonomy Process',
  'Definition': 'Comprehensive List of all Values utilized in Organizational Taxonomy in the Column Process',
  'publish': 1,
  'python_object': ['Algorithm Classification',
   'Algorithm Taxonomy',
   'Behavioural Economics',
   'Best Linear Unbiased Estimator',
   'Categorization Filter Order',
   'Data Collection',
   'Data Dictionary Columns',
   'Data Preparation',
   'Default Python String Taxonomy',
   'Documentation Taxonomy Categorization',
   'Dot Py String Classification',
   'Dot Py String Taxonomy Categorization',
   'Feature Engineering',
   'General Definition',
   'Goal Setting',
   'Machine Learning Lifecycle',
   'Mathematics',
   'Model Evaluation',
   'Problem Definition',
   'Problem Solving Framework',
   'Statistics']},
 'csv_links': {'Process': 'CSV Links',
  'Categorization': 'Reference Dictionary',
  'Word': 'CSV Links',
  'Definition': 'Dictionary of Links to Google Sheet, Git Hub and other pertinent datasource',
  'publish': 0,
  'python_object': {'google_definition_csv': 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQq1-3cTas8DCWBa2NKYhVFXpl8kLaFDohg0zMfNTAU_Fiw6aIFLWfA5zRem4eSaGPa7UiQvkz05loW/pub?output=csv',
   'google_notes_csv': 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSQF2lNc4WPeTRQ_VzWPkqSZp4RODFkbap8AqmolWp5bKoMaslP2oRVVG21x2POu_JcbF1tGRcBgodu/pub?output=csv',
   'google_word_quote': 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTjXiFjpGgyqWDg9RImj1HR_BeriXs4c5-NSJVwQFn2eRKksitY46oJT0GvVX366LO-m1GM8znXDcBp/pub?gid=1117793378&single=true&output=csv',
   'google_daily_activities': 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTjXiFjpGgyqWDg9RImj1HR_BeriXs4c5-NSJVwQFn2eRKksitY46oJT0GvVX366LO-m1GM8znXDcBp/pub?gid=472900611&single=true&output=csv',
   'technical_notes': 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSnwd-zccEOQbpNWdItUG0qXND5rPVFbowZINjugi15TdWgqiy3A8eMRhbmSMBiRhHt1Qsry3E8tKY8/pub?output=csv',
   'd_links': 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTjXiFjpGgyqWDg9RImj1HR_BeriXs4c5-NSJVwQFn2eRKksitY46oJT0GvVX366LO-m1GM8znXDcBp/pub?gid=469651051&single=true&output=csv',
   'function_list_url': 'https://raw.githubusercontent.com/derek-dewald/Python_Tools/main/Streamlit/DataDictionary/python_function_list.csv',
   'parameter_list_url': 'https://raw.githubusercontent.com/derek-dewald/Python_Tools/main/Streamlit/DataDictionary/python_function_parameters.csv',
   'folder_toc_url': 'https://raw.githubusercontent.com/derek-dewald/Python_Tools/main/Streamlit/DataDictionary/folder_listing.csv',
   'd_knowledge_base_url': 'https://raw.githubusercontent.com/derek-dewald/Python_Tools/main/Streamlit/DataDictionary/d_knowledge_base.csv',
   'process_cl': 'https://raw.githubusercontent.com/derek-dewald/Python_Tools/main/Data/d_knowledge_process_checklist.csv',
   'SKlearn Model Parameters': 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSnzcSYTXm2jl9GXvrNaH3b3TPbNufGJwRTMeJ8Ckhse_r9CWGjlXWlUfyGTwcnoXqT7ZLLyBAk2rKO/pub?gid=175044227&single=true&output=csv',
   'Sklearn Models': 'https://docs.google.com/spreadsheets/d/e/2PACX-1vToNab_ADzmxRZkg4bJ5wOwLZcrdwNYrxwWBETdGlfGSoUpnyy799EpbYqDqnwyKs2bEyJHUu58SX8Q/pub?gid=1125524518&single=true&output=csv'}},
 'url_links': {'Process': 'URL Links',
  'Categorization': 'Reference Dictionary',
  'Word': 'URL Links',
  'Definition': 'Dictionary of Links to Google Sheet, Git Hub and other pertinent datasource',
  'publish': 0,
  'python_object': {'google_definition_csv': 'https://docs.google.com/spreadsheets/d/1tZ-_5Vv99_bm9CCEdDDN0KkmsFNcjWeKM86237yrCTQ/edit?gid=0#gid=0',
   'google_notes_csv': 'https://docs.google.com/spreadsheets/d/1jddkkF5IWRr_eV1hTjB-T_IlmGJ-GpizYgeMgZQQxb4/edit?gid=0#gid=0',
   'technical_notes': 'https://docs.google.com/spreadsheets/d/1FpYYq4LN6AZBaNRhnj1f76YNvnG-hTco40wJ1PUugto/edit?gid=0#gid=0',
   'd_links': 'https://docs.google.com/spreadsheets/d/14CtNmNIajcY1mlEkRWw4ka93MQYGs2wN-kvL5qhvQX0/edit?gid=469651051#gid=469651051',
   'Job Search': 'https://docs.google.com/spreadsheets/d/1sMdgmp80DXDojDl6uYS6INdoJxVDbhIwpwCtpxBjHVg/edit?gid=668067090#gid=668067090',
   'OurWorldData': 'www.ourworlddata.org',
   'KaggelDatasets': 'https://www.kaggle.com/datasets',
   'StLouisFed': 'https://fred.stlouisfed.org',
   'GoggleResearch': 'https://datasetsearch.research.google.com',
   'UCI': 'https://archive.ics.uci.edu',
   'AWS': 'https://registry.opendata.aws/',
   'AWSDataExchange': 'https://aws.amazon.com/data-exchange/',
   'AWSPublicData': 'https://aws.amazon.com/public-datasets/',
   'SKlearn Model Parameters': 'https://docs.google.com/spreadsheets/d/1GhIiuEMY-A-SNtQOj5Z24wARLVGvEd10qVT3MpGtj2Y/edit?gid=175044227#gid=175044227',
   'TensorFlow Playground': 'https://playground.tensorflow.org/',
   'SQL Cheatsheet': 'https://raw.githubusercontent.com/derek-dewald/d_functions/main/images/SQL_Cheatsheet.png'}}}

In [16]:
df = pd.DataFrame(object_dict.values())
df['key'] = object_dict.keys()

final_df = pd.DataFrame()

for item in df[df['publish']==1]['key']:
    temp = object_dict[item]
    temp_df = pd.DataFrame(temp['python_object'],columns=['Word'])
    temp_df['Categorization'] = temp['Categorization']
    temp_df['Process'] = temp['Process']
    temp_df['Definition'] = ""
    temp_df.loc[len(temp_df)] = {
        "Process": temp['Process'],
        "Categorization": "Definition",
        "Word": 'General Definition',
        "Definition": temp['Definition']}
    final_df = pd.concat([final_df,temp_df])    


#########
# Do I need to remove Order from Definitions
#########

final_df['Order'] = final_df.groupby(['Process']).cumcount()+1
final_df['Categorization'] = np.where(final_df['Categorization']=='Process','Process Step',final_df['Categorization'])

final_df

,Word,Categorization,Process,Definition,Order
0,Directory Management,Reference List,Dot Py String Taxonomy Categorization,,1
1,File Management,Reference List,Dot Py String Taxonomy Categorization,,2
2,Excel File Creation,Reference List,Dot Py String Taxonomy Categorization,,3
3,Definition,Reference List,Dot Py String Taxonomy Categorization,,4
4,Manual File Creator,Reference List,Dot Py String Taxonomy Categorization,,5
5,General Definition,Definition,Dot Py String Taxonomy Categorization,Comprehensive List of all Values utilized in O...,6
0,Algorithm Classification,Reference List,Documentation Taxonomy Categorization,,1
1,Algorithm Taxonomy,Reference List,Documentation Taxonomy Categorization,,2
2,Behavioural Economics,Reference List,Documentation Taxonomy Categorization,,3
3,Best Linear Unbiased Estimator,Reference List,Documentation Taxonomy Categorization,,4
4,Categorization Filter Order,Reference List,Documentation Taxonomy Categorization,,5
5,Data Collection,Reference List,Documentation Taxonomy Categorization,,6
6,Data Dictionary Columns,Reference List,Documentation Taxonomy Categorization,,7
7,Data Preparation,Reference List,Documentation Taxonomy Categorization,,8
8,Default Python String Taxonomy,Reference List,Documentation Taxonomy Categorization,,9
9,Documentation Taxonomy Categorization,Reference List,Documentation Taxonomy Categorization,,10
10,Dot Py String Classification,Reference List,Documentation Taxonomy Categorization,,11
11,Dot Py String Taxonomy Categorization,Reference List,Documentation Taxonomy Categorization,,12
12,Feature Engineering,Reference List,Documentation Taxonomy Categorization,,13
13,General Definition,Reference List,Documentation Taxonomy Categorization,,14
14,Goal Setting,Reference List,Documentation Taxonomy Categorization,,15
15,Machine Learning Lifecycle,Reference List,Documentation Taxonomy Categorization,,16
16,Mathematics,Reference List,Documentation Taxonomy Categorization,,17
17,Model Evaluation,Reference List,Documentation Taxonomy Categorization,,18
18,Problem Definition,Reference List,Documentation Taxonomy Categorization,,19
19,Problem Solving Framework,Reference List,Documentation Taxonomy Categorization,,20
20,Statistics,Reference List,Documentation Taxonomy Categorization,,21
21,General Definition,Definition,Documentation Taxonomy Categorization,Comprehensive List of all Values utilized in O...,22

In [ ]:

def extract_object_dot_py(
    object_dict,
    export_location):
    
    '''
    Definition:
        Generate an Excel file of all parameters which are manually stored and maintained. File which is generated is used a input component for generate_knowledgebase.
    
    Parameters:
        object_dict (dict): Dictionary Object from either objects_manual or objects_automated
        export_location(str): Location where .xlsx file will be saved. 

    Returns:
        df

    date_created:29-Jun-26
    date_last_modified: 3-Jul-26
    classification:TBD
    sub_classification:TBD
    usage:
        manual_object_df(object_dict_manual,'/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/object_manual_published.xlsx')
    update:
        Added Definition as new record, added column definition.
        To support Automated Object included dict Argument in Required definitions, removed default string
    
    '''

    df = pd.DataFrame(object_dict.values())
    df['key'] = object_dict.keys()
    
    final_df = pd.DataFrame()
    
    for item in df[df['publish']==1]['key']:
        temp = object_dict[item]
        temp_df = pd.DataFrame(temp['python_object'],columns=['Word'])
        temp_df['Categorization'] = temp['Categorization']
        temp_df['Process'] = temp['Process']
        temp_df['Definition'] = ""
        temp_df.loc[len(temp_df)] = {
            "Process": temp['Process'],
            "Categorization": "Definition",
            "Word": 'General Definition',
            "Definition": temp['Definition']}
        final_df = pd.concat([final_df,temp_df])    


    #########
    # Do I need to remove Order from Definitions
    #########
    
    final_df['Order'] = final_df.groupby(['Process']).cumcount()+1
    final_df['Categorization'] = np.where(final_df['Categorization']=='Process','Process Step',final_df['Categorization'])

    # is Manual Published, Need Order
    if export_location.find('object_manual_published')!=-1:
        final_df[['Process','Categorization','Word','Definition','Order']].to_excel(export_location,index=False)
    else:
        final_df[['Process','Categorization','Word','Definition']].to_excel(export_location,index=False)

In [17]:
definition_df = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vQq1-3cTas8DCWBa2NKYhVFXpl8kLaFDohg0zMfNTAU_Fiw6aIFLWfA5zRem4eSaGPa7UiQvkz05loW/pub?output=csv')
definition_df

,Process,Categorization,Word,Definition,Notes,Link,Image,Markdown Equation,Dataset Size,Learning Type,Algorithm Classification,Model Type
0,Behavioural Economics,Concept,Anchoring Effect,A cognitive bias where people rely too heavily...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Behavioural Economics,Concept,Base Rate Fallacy,People ignore or undervalue general statistica...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Behavioural Economics,Concept,Bureaucratic Politics,Organization decision making paradigm in which...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Behavioural Economics,Concept,Biased Assimilation,Tendency to interpret information in a way tha...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Behavioural Economics,Concept,Blind spot bias,Cognitive bias where people are unaware of the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
108,Algorithm Categorization,Definition,Graph Algorithms,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,Algorithm Categorization,Definition,Prediction,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110,Algorithm Taxonomy,Definition,Algorithm Parent Category,A broad domain describing the general purpose ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,Algorithm Taxonomy,Definition,Algorithm Categorization,The type of computational problem or objective...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,Algorithm Taxonomy,Definition,Method,"A specific computational approach, algorithm, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
algo_class_list = definition_df[definition_df['Process']=='Algorithm Categorization']['Word'].unique().tolist()
algo_class_list.sort()
algo_class_list

['Anomaly Detection',
 'Classification',
 'Clustering',
 'Density Estimation',
 'Dimensionality Reduction',
 'Feature Selection',
 'Feature Transformation',
 'Generative Models',
 'Graph Algorithms',
 'Information Retrieval',
 'Optimization',
 'Prediction',
 'Ranking / Recommendation',
 'Regression',
 'Reinforcement Learning',
 'Time Series Forecasting']

In [24]:

generate_objects_automated_py()