In [ ]:
## MAKE NOTES ABOUT KNOWLEDGE BASE. 
# SPECIFICALLY IF I PROCESS NOT GENERAL DEFINITION IT WILL BE BROUGHT OVER. 
# General Definition it will only include if already Included

In [ ]:
# Change the Length of the Columns in the Dashboard.
# Filtering Order for Processes and Categorization is not great for anything that isn't a Formal PRocess with Process steps.
# Should be able to add an additional layer, so when there is #NA in orignal columns it still works.

#  Build a process for Specific Types of ML Procesess, Clustering to incorporate additional features into process - Convoluted as normal step.

In [1]:
import pandas as pd
import numpy as np
import sys

sys.path.append("/Users/derekdewald/Documents/Python/Github_Repo/d_py_functions")

In [7]:
object_dict['csv_links']['python_object']['google_definition_csv']

'https://docs.google.com/spreadsheets/d/e/2PACX-1vQq1-3cTas8DCWBa2NKYhVFXpl8kLaFDohg0zMfNTAU_Fiw6aIFLWfA5zRem4eSaGPa7UiQvkz05loW/pub?output=csv'

In [3]:
#from daily_etl_folder_mgmt import ETL
#ETL()

python_function_list Saved to /Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/
python_function_parameters Saved to /Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/

In [13]:
from objects_automated import object_dict

#links = pd.read_csv(object_dict['csv_links']['python_object']['d_links'])
notes = pd.read_csv(object_dict['csv_links']['python_object']['google_notes_csv'])
definitions = pd.read_csv(object_dict['csv_links']['python_object']['google_definition_csv'])
#technical_notes = pd.read_csv(object_dict['csv_links']['python_object']['technical_notes'])

In [14]:
from daily_etl_folder_mgmt import generate_files_for_streamlit

knowledge_base_df= generate_files_for_streamlit(
    definition_df=definitions,
    notes_df=notes
)

In [22]:
knowledge_base_df[
    (knowledge_base_df['Process']=='Machine Learning Lifecycle')&(
        (knowledge_base_df['Categorization']==word)|
        (knowledge_base_df['Word']==word)
)
]

,Process,Categorization,Word,Definition,Source
789,Machine Learning Lifecycle,Process Step,Data Collection,"Data collection involves identifying, sourcing...",Knowledge Base
790,Machine Learning Lifecycle,Data Collection,Semantic Classification,Establish a consistent understanding of what i...,LVL1
791,Machine Learning Lifecycle,Data Collection,Problem Decomposition,Break the analytical problem into the distinct...,LVL1
792,Machine Learning Lifecycle,Data Collection,Variable Mapping,Connect the conceptual information requirement...,LVL1
793,Machine Learning Lifecycle,Data Collection,Gap Assessment,Evaluate the extent to which the available dat...,LVL1
794,Machine Learning Lifecycle,Data Collection,Label Data,Ensure that All data is defined and classified...,LVL1
795,Machine Learning Lifecycle,Data Collection,Ensure Sufficient Data Exists,Ensure that model has sufficient representatio...,LVL1
796,Machine Learning Lifecycle,Data Collection,Challenges from Missing Data,What concessions have we made due to a lack of...,LVL1
797,Machine Learning Lifecycle,Data Collection,Who Owns the Data,Who is the Data Steward and Process owners? Ar...,LVL1
798,Machine Learning Lifecycle,Data Collection,Functional Role,Describes how a variable is used within a spec...,LVL1
799,Machine Learning Lifecycle,Data Collection,Semantic Type,Describes the meaning or nature of a variable ...,LVL1

In [18]:
word = 'Data Collection'
knowledge_base_df[(knowledge_base_df['Process']==word)|(knowledge_base_df['Categorization']==word)]

,Process,Categorization,Word,Definition,Source
443,Data Collection,Process,Definition,"Data collection involves identifying, sourcing...",Knowledge Base
444,Data Collection,Taxonomy,Semantic Classification,Establish a consistent understanding of what i...,Knowledge Base
445,Data Collection,Taxonomy,Problem Decomposition,Break the analytical problem into the distinct...,Knowledge Base
446,Data Collection,Taxonomy,Variable Mapping,Connect the conceptual information requirement...,Knowledge Base
447,Data Collection,Taxonomy,Gap Assessment,Evaluate the extent to which the available dat...,Knowledge Base
448,Data Collection,Process Step,Label Data,Ensure that All data is defined and classified...,Knowledge Base
449,Data Collection,Process Step,Ensure Sufficient Data Exists,Ensure that model has sufficient representatio...,Knowledge Base
450,Data Collection,Warning,Challenges from Missing Data,What concessions have we made due to a lack of...,Knowledge Base
451,Data Collection,Consideration,Who Owns the Data,Who is the Data Steward and Process owners? Ar...,Knowledge Base
452,Data Collection,Process Step,Functional Role,Describes how a variable is used within a spec...,Knowledge Base
453,Data Collection,Functional Role,Core Variables,Primary variables that directly shape model ou...,LVL1
454,Data Collection,Functional Role,Supporting,Variables that contribute to model quality but...,LVL1
455,Data Collection,Functional Role,Explanatory,Variables used to understand and communicate m...,LVL1
456,Data Collection,Functional Role,Monitoring,"Variables used to assess model behaviour, stab...",LVL1
457,Data Collection,Process Step,Semantic Type,Describes the meaning or nature of a variable ...,Knowledge Base
458,Data Collection,Semantic Type,State,Represents the current condition of an entity ...,LVL1
459,Data Collection,Semantic Type,Descriptive,Represents summarized or smoothed behaviour ov...,LVL1
460,Data Collection,Semantic Type,Diagnostic,Represents how an entity's behaviour changes t...,LVL1
461,Data Collection,Semantic Type,Diagnostic: Change,Measures the difference in a value between two...,LVL1
462,Data Collection,Semantic Type,Diagnostic: Trend,Represents the overall direction and pattern o...,LVL1
463,Data Collection,Semantic Type,Diagnostic: Momentum,Measures acceleration or deceleration in an en...,LVL1
464,Data Collection,Semantic Type,Diagnostic: Volatility,"Measures how variable, irregular, or unpredict...",LVL1
465,Data Collection,Semantic Type,Structural,Represents relatively stable attributes descri...,LVL1
466,Data Collection,Semantic Type,Contextual,Represents external or situational factors tha...,LVL1
467,Data Collection,Semantic Type,Demographic,Represents relatively stable attributes descri...,LVL1
468,Data Collection,Semantic Type,Constraint,Represents factors that restrict or enable the...,LVL1
469,Data Collection,Semantic Type,Constraint: Capacity,Represents fundamental limits on what an entit...,LVL1
470,Data Collection,Semantic Type,Constraint: Stability & Fragility,Represents the reliability and resilience of a...,LVL1
471,Data Collection,Semantic Type,Constraint: Access & Configuration,Represents limitations or opportunities create...,LVL1
472,Data Collection,Semantic Type,Constraint: Stress & Load,Represents sustained pressure that restricts f...,LVL1
473,Data Collection,Semantic Type,Constraint: Time & Commitment,"Represents contractual, recurring, or long-ter...",LVL1
790,Machine Learning Lifecycle,Data Collection,Semantic Classification,Establish a consistent understanding of what i...,LVL1
791,Machine Learning Lifecycle,Data Collection,Problem Decomposition,Break the analytical problem into the distinct...,LVL1
792,Machine Learning Lifecycle,Data Collection,Variable Mapping,Connect the conceptual information requirement...,LVL1
793,Machine Learning Lifecycle,Data Collection,Gap Assessment,Evaluate the extent to which the available dat...,LVL1
794,Machine Learning Lifecycle,Data Collection,Label Data,Ensure that All data is defined and classified...,LVL1
795,Machine Learning Lifecycle,Data Collection,Ensure Sufficient Data Exists,Ensure that model has sufficient representatio...,LVL1
796,Machine Learning Lifecycle,Data Collection,Challenges from Missing Data,What concessions have we made due to a lack of...,LVL1
797,Machine Learning Lifecycle,Data Collection,Who Owns the Data,Who is the Data Steward and Process owners? Ar...,LVL1
798,Machine Learning Lifecycle,Data Collection,Functional Role,Describes how a variable is used within a spec...,LVL1
799,Machine Learning Lifecycle,Data Collection,Semantic Type,Describes the meaning or nature of a variable ...,LVL1

In [10]:
from daily_etl_folder_mgmt import extract_object_dot_py
from objects_automated import object_dict as object_dict_auto
from objects_manual import object_dict as object_dict_man

extract_object_dot_py(object_dict_man,'/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/object_manual_published.xlsx')
extract_object_dot_py(object_dict_auto,'/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/object_auto_published.xlsx')

In [3]:
from daily_etl_folder_mgmt import generate_objects_automated_py
generate_objects_automated_py()

In [10]:
consolidated_xlsx = '/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/consolidated_dataset.xlsx'
consolidated_df = pd.read_excel(consolidated_xlsx)

In [11]:
consolidated_df[consolidated_df['Process']=='Algorithm Classification']

,Process,Categorization,Word,Definition,Location
120,Algorithm Classification,Definition,Anomaly Detection,Algorithm which designed to identify observati...,Definitions
121,Algorithm Classification,Definition,Classification,Algorithm which assign observations to one of ...,Definitions
122,Algorithm Classification,Definition,Clustering,Algorithm which group observations into cluste...,Definitions
123,Algorithm Classification,Definition,Regression,Algorithm which predict continuous numerical v...,Definitions
124,Algorithm Classification,Definition,Ranking / Recommendation,Algorithm which order items or suggest relevan...,Definitions
125,Algorithm Classification,Definition,Density Estimation,Approaches which involve modeling the underlyi...,Definitions
126,Algorithm Classification,Definition,Dimensionality Reduction,Algorithm which reduce the number of variables...,Definitions
127,Algorithm Classification,Definition,Feature Selection,Methods that identify and retain a subset of e...,Definitions
128,Algorithm Classification,Definition,Feature Transformation,Methods which modify existing features into ne...,Definitions
129,Algorithm Classification,Definition,Information Retrieval,NaN,Definitions
130,Algorithm Classification,Definition,Time Series Forecasting,NaN,Definitions
131,Algorithm Classification,Definition,Generative Models,NaN,Definitions
132,Algorithm Classification,Definition,Reinforcement Learning,NaN,Definitions
133,Algorithm Classification,Definition,Optimization,NaN,Definitions
134,Algorithm Classification,Definition,Graph Algorithms,NaN,Definitions
135,Algorithm Classification,Definition,Prediction,NaN,Definitions

In [ ]:
from daily_processes import daily_test
daily_test()

In [ ]:
# Generate Python File Including All Dictionaries

from dict_processing import dict_defitions_dot_py
dict_defitions_dot_py()