In [ ]:
## MAKE NOTES ABOUT KNOWLEDGE BASE. 
# SPECIFICALLY IF I PROCESS NOT GENERAL DEFINITION IT WILL BE BROUGHT OVER. 
# General Definition it will only include if already Included

In [ ]:
# Change the Length of the Columns in the Dashboard.
# Filtering Order for Processes and Categorization is not great for anything that isn't a Formal PRocess with Process steps.
# Should be able to add an additional layer, so when there is #NA in orignal columns it still works.

#  Build a process for Specific Types of ML Procesess, Clustering to incorporate additional features into process - Convoluted as normal step.

In [ ]:
    with c4:
        c4_options = ["(All)"] + sorted([x for x in df3[c4_word].unique() if x.strip()])
        c4_sel = st.selectbox(c4_word, c4_options, index=0)

    df_view = df3 if c4_sel == "(All)" else df3[df3[c4_word] == c4_sel]

    if definition_search.strip():
        s = definition_search.strip().lower()
        df_view = df_view[df_view[search_word].str.lower().str.contains(s, na=False)]

In [ ]:

# -----------------------------------
# Processes
# -----------------------------------

elif page == 'Processes':
    st.title("Processes")
    df_base = data_dict['processes_df'].copy()
    c1, c2, c3, c4 = st.columns([1, 1, 1, 2])

    c1_word = 'Process'
    c2_word = 'Categorization'
    c3_word = 'Word'
    search_word = 'Definition'

    with c1:
        c1_options = ["(All)"] + sorted([x for x in df_base[c1_word].unique() if x.strip()])
        c1_sel = st.selectbox(c1_word, c1_options, index=0)

    df1 = df_base if c1_sel == "(All)" else df_base[df_base[c1_word] == c1_sel]

    with c2:
        c2_options = ["(All)"] + sorted([x for x in df1[c2_word].unique() if x.strip()])
        c2_sel = st.selectbox(c2_word, c2_options, index=0)

    df2 = df1 if c2_sel == "(All)" else df1[df1[c2_word] == c2_sel]

    with c3:
        c3_options = ["(All)"] + sorted([x for x in df2[c3_word].unique() if x.strip()])
        c3_sel = st.selectbox(c3_word, c3_options, index=0)

    df3 = df2 if c3_sel == "(All)" else df2[df2[c3_word] == c3_sel]

    with c4:
        definition_search = st.text_input("Definition search", value="", placeholder="Type to search Description...")

    df_view = df3
    if definition_search.strip():
        s = definition_search.strip().lower()
        df_view = df_view[df_view[search_word].str.lower().str.contains(s, na=False)]

    st.caption(f"Rows: {len(df_view)}")

    excel_bytes = df_to_excel_bytes(
        df_view,
        sheet_name="Processes",
        long_columns=["Definition"],
        default_max_width=30,
        long_max_width=80
    )

    st.download_button(
        label="Download filtered Processes as Excel",
        data=excel_bytes,
        file_name="filtered_processes.xlsx",
        mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")

    gb = GridOptionsBuilder.from_dataframe(df_view)

    gb.configure_default_column(
        resizable=True,
        sortable=True,
        filter=True,
        wrapText=True,
        autoHeight=True
    )

    gb.configure_column(c1_word, width=100, minWidth=80, maxWidth=120)
    gb.configure_column(c2_word, width=100, minWidth=80, maxWidth=120)
    gb.configure_column(c3_word, width=150, minWidth=120, maxWidth=170)

    gb.configure_column(
        search_word,
        flex=1,
        minWidth=700,
        wrapText=True,
        autoHeight=True
    )

    gridOptions = gb.build()

    gridOptions["onGridReady"] = on_grid_ready
    gridOptions["onGridSizeChanged"] = on_grid_size_changed

    AgGrid(
        df_view,
        gridOptions=gridOptions,
        height=800,
        allow_unsafe_jscode=True,
        fit_columns_on_grid_load=False,
        reload_data=True,
    )

# -----------------------------------
# Process and Categorization Utilization
# -----------------------------------

elif page == 'Process Checklist':
    st.title("Process Checklist")
    df_base = data_dict['consolidated_df'].copy()

    p_list = df_base[df_base['Categorization']=='Process']['Process'].drop_duplicates().unique().tolist()
    df_base = df_base[df_base['Process'].isin(p_list)].copy()

    c1, c2, c3, c4 = st.columns([1, 1, 1, 1])

    c1_word = 'Process'
    c2_word = 'Categorization'

    with c1:
        c1_options = ["(All)"] + sorted([x for x in df_base[c1_word].unique() if x.strip()])
        c1_sel = st.selectbox(c1_word, c1_options, index=0)

    df1 = df_base if c1_sel == "(All)" else df_base[df_base[c1_word] == c1_sel]

    with c2:
        c2_options = ["(All)"] + sorted([x for x in df1[c2_word].unique() if x.strip()])
        c2_sel = st.selectbox(c2_word, c2_options, index=0)

    df2 = df1 if c2_sel == "(All)" else df1[df1[c2_word] == c2_sel]

    df_view = df2[['Process','Categorization','Word','Definition']]

    st.caption(f"Rows: {len(df_view)}")

    excel_bytes = df_to_excel_bytes(
        df_view,
        sheet_name="Processes",
        long_columns=["Definition"],
        default_max_width=30,
        long_max_width=80
    )

    st.download_button(
        label="Download filtered Processes as Excel",
        data=excel_bytes,
        file_name="filtered_processes.xlsx",
        mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")

    gb1 = GridOptionsBuilder.from_dataframe(df_view)

    gb1.configure_default_column(
        resizable=True,
        sortable=True,
        filter=True,
        wrapText=True,
        autoHeight=True
    )

    gb1.configure_column(c1_word, width=100, minWidth=80, maxWidth=120)
    gb1.configure_column(c2_word, width=100, minWidth=80, maxWidth=120)
    gb1.configure_column('Word', width=150, minWidth=120, maxWidth=170)

    gb1.configure_column(
        "Definition",
        flex=1,
        minWidth=700,
        wrapText=True,
        autoHeight=True
    )

    gridOptions = gb1.build()

    gridOptions["onGridReady"] = on_grid_ready
    gridOptions["onGridSizeChanged"] = on_grid_size_changed

    AgGrid(
        df_view,
        gridOptions=gridOptions,
        height=800,
        allow_unsafe_jscode=True,
        fit_columns_on_grid_load=False,
        reload_data=True,
    )

In [1]:
import pandas as pd
import numpy as np
import sys

sys.path.append("/Users/derekdewald/Documents/Python/Github_Repo/d_py_functions")

In [2]:
from daily_etl_folder_mgmt import generate_files_for_streamlit

knowledge_base_df= generate_files_for_streamlit()

In [3]:
knowledge_base_df

,Process,Categorization,Word,Definition,Source
0,Activation Function,Training,Leaky Relu,,Knowledge Base
1,Activation Function,Training,Relu,,Knowledge Base
2,Activation Function,Training,Sigmoid,,Knowledge Base
3,Activation Function,Training,Softmax,,Knowledge Base
4,Activation Function,Training,Tanh,,Knowledge Base
...,...,...,...,...,...
393,Understand Your Visuals,Guidance,"Interesting and Engaging Visuals, Minimal Words.",80% Salient might be better than 100% accurate,Knowledge Base
394,Understand Your Visuals,Process Step,Simplicity over Complexity,Are they Simple and Clear?,Knowledge Base
395,Understand Your Visuals,Guidance,Will they understand?,"People are easily distractible, so they might ...",Knowledge Base
396,Understand Your Visuals,Guidance,Eyes Not Minds,,Knowledge Base
397,Validation,Process,Definition,Validation is the process of assessing model p...,Knowledge Base

In [4]:
knowledge_base_df

,Process,Categorization,Word,Definition
0,Goal Setting,Process,Definition,"Thought process utilized to establish a clear,..."
1,Problem Definition,Process,Definition,"A Clear, Concise and explicit definition of th..."
2,Data Collection,Process,Definition,"Data collection involves identifying, sourcing..."
3,Data Preparation,Process,Definition,Data preparation focuses on cleaning and struc...
4,Exploratory Data Analysis,Process,Definition,Foundational step in ensuring the success of a...
...,...,...,...,...
246,Understand Your Audience,Process Step,What do they want?,The more we know about the motivations and inc...
247,Understand Your Audience,Process Step,Are they likely to Care?,
248,Understand Your Audience,Example,Getting CEO to Pick,How to get a CEO to remove a soft drink from J...
249,Understand Your Audience,Consideration,Stress Induced U Curve,High Pressure Decision Making: The inverted U ...
250,Understand Your Audience,Example,Cuban Missile Crisis,"Asymmetric Information, Deception, Misreading ..."

In [6]:
consolidated_df[consolidated_df['Process']=='']

    Process Categorization Word Definition
0
1
2
3
4
..      ...            ...  ...        ...
251
252
253
254
255

[264 rows x 4 columns]

In [4]:
consolidated_df[consolidated_df['Process']=='Communication']

,Process,Categorization,Word,Definition
35,Communication,Process,Definition,
36,Communication,Process Step,Understand Your Message,
37,Communication,Process Step,Understand Your Audience,
38,Communication,Process Step,Understand Your Strategy,"Beyond understanding Your Message, you need to..."
39,Communication,Process Step,Choosing a Medium,"While not always give a choice, it is importan..."
40,Communication,Process Step,Understand Your Visuals,
41,Communication,Process Step,Message Spareness,"Utilize a less is more approach, whether that ..."
42,Communication,Process Step,Re-enforce the Message,
43,Communication,Process Step,Cardinal Communication Sins,
44,Communication,Cardinal Communication Sins,Deliver Simplicity,Do not make the user think
45,Communication,Cardinal Communication Sins,Do Not Demand Recall,Do not make the user remember. If the Speaker ...
46,Communication,Cardinal Communication Sins,Visuals in 2D,Do not use 3D unless absolutely necessary.
47,Communication,Cardinal Communication Sins,Avoid Pie Charts,Pie Charts. They Suck.
48,Communication,Cardinal Communication Sins,Do Not Offend Your Audience,
49,Communication,Cardinal Communication Sins,Do Not Let Predjudices Close Your Mind,
50,Communication,Cardinal Communication Sins,Don’t waste the advantage that thought has ove...,
51,Communication,Cardinal Communication Sins,Hearing vs Listening,"Most were born hearing well, EVERYONE must lea..."
52,Communication,Cardinal Communication Sins,Always Thank Your Audience,
53,Communication,Process Step,General Expectations,
54,Communication,Process Step,Measuing Effectiveness,How can one measure how effective/ineffective ...

In [5]:
consolidated_df[consolidated_df['Process']=='Machine Learning Lifecycle']

,Process,Categorization,Word,Definition
104,Machine Learning Lifecycle,Process,Definition,To Be Defined
105,Machine Learning Lifecycle,Process Step,Goal Setting,"Thought process utilized to establish a clear,..."
106,Machine Learning Lifecycle,Goal Setting,Specific,Describes what will be accomplished and what s...
107,Machine Learning Lifecycle,Goal Setting,Measurable,Includes a clear way to track progress or dete...
108,Machine Learning Lifecycle,Goal Setting,Achievable,"Realistic given available time, resources, ski..."
...,...,...,...,...
192,Machine Learning Lifecycle,Monitoring,Clearly define production context windows,Define triggers for retraining or model review...
193,Machine Learning Lifecycle,Process Step,"Bias, Fairness, and Ethics",This step examines whether the model produces ...
194,Machine Learning Lifecycle,"Bias, Fairness, and Ethics",Review Demographics,Evaluate model performance across key demograp...
195,Machine Learning Lifecycle,"Bias, Fairness, and Ethics",Test unitended discrimination,Review sensitive features and proxy variables....
196,Machine Learning Lifecycle,"Bias, Fairness, and Ethics",Document Fairness Checks,Document fairness checks and mitigation steps....

In [3]:
#from daily_etl_folder_mgmt import ETL
#ETL()

python_function_list Saved to /Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/
python_function_parameters Saved to /Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/

In [3]:
from objects_automated import object_dict

links = pd.read_csv(object_dict['csv_links']['python_object']['d_links'])
notes = pd.read_csv(object_dict['csv_links']['python_object']['google_notes_csv'])
definitions = pd.read_csv(object_dict['csv_links']['python_object']['google_definition_csv'])
technical_notes = pd.read_csv(object_dict['csv_links']['python_object']['technical_notes'])

In [10]:
from daily_etl_folder_mgmt import extract_object_dot_py
from objects_automated import object_dict as object_dict_auto
from objects_manual import object_dict as object_dict_man

extract_object_dot_py(object_dict_man,'/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/object_manual_published.xlsx')
extract_object_dot_py(object_dict_auto,'/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/object_auto_published.xlsx')

In [3]:
from daily_etl_folder_mgmt import generate_objects_automated_py
generate_objects_automated_py()

In [10]:
consolidated_xlsx = '/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/consolidated_dataset.xlsx'
consolidated_df = pd.read_excel(consolidated_xlsx)

In [11]:
consolidated_df[consolidated_df['Process']=='Algorithm Classification']

,Process,Categorization,Word,Definition,Location
120,Algorithm Classification,Definition,Anomaly Detection,Algorithm which designed to identify observati...,Definitions
121,Algorithm Classification,Definition,Classification,Algorithm which assign observations to one of ...,Definitions
122,Algorithm Classification,Definition,Clustering,Algorithm which group observations into cluste...,Definitions
123,Algorithm Classification,Definition,Regression,Algorithm which predict continuous numerical v...,Definitions
124,Algorithm Classification,Definition,Ranking / Recommendation,Algorithm which order items or suggest relevan...,Definitions
125,Algorithm Classification,Definition,Density Estimation,Approaches which involve modeling the underlyi...,Definitions
126,Algorithm Classification,Definition,Dimensionality Reduction,Algorithm which reduce the number of variables...,Definitions
127,Algorithm Classification,Definition,Feature Selection,Methods that identify and retain a subset of e...,Definitions
128,Algorithm Classification,Definition,Feature Transformation,Methods which modify existing features into ne...,Definitions
129,Algorithm Classification,Definition,Information Retrieval,NaN,Definitions
130,Algorithm Classification,Definition,Time Series Forecasting,NaN,Definitions
131,Algorithm Classification,Definition,Generative Models,NaN,Definitions
132,Algorithm Classification,Definition,Reinforcement Learning,NaN,Definitions
133,Algorithm Classification,Definition,Optimization,NaN,Definitions
134,Algorithm Classification,Definition,Graph Algorithms,NaN,Definitions
135,Algorithm Classification,Definition,Prediction,NaN,Definitions

In [ ]:
from daily_processes import daily_test
daily_test()

In [ ]:
# Generate Python File Including All Dictionaries

from dict_processing import dict_defitions_dot_py
dict_defitions_dot_py()