### Daily Process

In [ ]:
import pandas as pd
import numpy as np
import sys
sys.path.append("/Users/derekdewald/Documents/Python/Github_Repo/d_py_functions")

# Update Manual Parameter List
from daily_etl_folder_mgmt import extract_object_dot_py,generate_knowledgebase,extract_consolidated_raw_dataset

'''
Daily Process - There is some cyclicality in it, in that objectes_automated is used to build knowledge_base, but it's requries an updated version of knowledge_base. So run process 

'''

# Import Data
notes_df = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vSQF2lNc4WPeTRQ_VzWPkqSZp4RODFkbap8AqmolWp5bKoMaslP2oRVVG21x2POu_JcbF1tGRcBgodu/pub?output=csv')
definition_df = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vQq1-3cTas8DCWBa2NKYhVFXpl8kLaFDohg0zMfNTAU_Fiw6aIFLWfA5zRem4eSaGPa7UiQvkz05loW/pub?output=csv')
manual_object_df = pd.read_excel('/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/object_manual_published.xlsx')

# Generate Knowledge Base
knowledge_base_df = generate_knowledgebase(
    notes_df=notes_df,
    definition_df=definition_df,
    export_location='/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/knowledge_base.xlsx')

# Update object_auto_published.xlsx based on Current Information 


df_dict = {
    'Notes':notes_df,
    'Definitions':definition_df,
    'Knowledge Base':knowledge_base_df,
    'Manual Objects':manual_object_df
}

# Update objects_automated.py
extract_consolidated_raw_dataset(df_dict,True)

# Re-import updated version of object_auto_published.xlsx, object_manual_published.xlsx
# Can't import files until this point or else it will include Historical Information
from objects_automated import object_dict as object_dict_auto
from objects_manual import object_dict as object_dict_man

# Generates Updated Versions of object_auto_published.xlsx, object_manual_published.xlsx based on the .py file. IT DOES NOT CHANGE the .py file
extract_object_dot_py(object_dict_man,'/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/object_manual_published.xlsx')
extract_object_dot_py(object_dict_auto,'/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/object_auto_published.xlsx')



auto_object_df = pd.read_excel('/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/object_auto_published.xlsx')
manual_object_df = pd.read_excel('/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/object_manual_published.xlsx')

knowledge_base_df = generate_knowledgebase(
    notes_df=notes_df,
    definition_df=definition_df,
    export_location='/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/knowledge_base.xlsx')

# Generate Define Processes 
knowledge_base_df[knowledge_base_df['Categorization']=='Process Step'].to_excel('/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/defined_processes.xlsx')

In [10]:
knowledge_base_df[knowledge_base_df['Categorization']=='Process Step'].to_excel('/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/defined_processes.xlsx')

In [9]:
knowledge_base_df[knowledge_base_df['Process']=='Data Collection']

,Process,Categorization,Word,Definition
23,Data Collection,Guidance,Challenges from Missing Data,What concessions have we made due to a lack of...
25,Data Collection,Guidance,Review Definitions,"Review Semantic and Functional Definitions, en..."
24,Data Collection,Guidance,Who is the Steward,"Who is the Data Steward, are they involved, an..."

,Process,Categorization,Word,Definition
69,Machine Learning Lifecycle,Process Step,Goal Setting,"Thought process utilized to establish a clear,..."
70,Machine Learning Lifecycle,Process Step,Problem Definition,"A Clear, Concise and explicit definition of th..."
145,Machine Learning Lifecycle,Process Step,Problem Definition,Desired State Metrics: Describe the target out...
147,Machine Learning Lifecycle,Process Step,Problem Definition,Current State Analysis: Describes how the proc...
149,Machine Learning Lifecycle,Process Step,Problem Definition,Root Cause Assessment: Identifies the underlyi...
151,Machine Learning Lifecycle,Process Step,Problem Definition,"Historical Overview: Summarizes what actions, ..."
153,Machine Learning Lifecycle,Process Step,Problem Definition,Baseline Metrics (Current State): Quantify the...
71,Machine Learning Lifecycle,Process Step,Data Collection,"Data collection involves identifying, sourcing..."
72,Machine Learning Lifecycle,Process Step,Data Preparation,Data preparation focuses on cleaning and struc...
73,Machine Learning Lifecycle,Process Step,Exploratory Data Analysis,Foundational step in ensuring the success of a...
74,Machine Learning Lifecycle,Process Step,Feature Engineering,Process of creating new input variables that b...
75,Machine Learning Lifecycle,Process Step,Feature Selection,Process of identifying and retaining the most ...
76,Machine Learning Lifecycle,Process Step,Model Selection,NaN
77,Machine Learning Lifecycle,Process Step,Training,Process of fitting a machine learning model to...
78,Machine Learning Lifecycle,Process Step,Hyperparameter Tuning,Optimizing the configuration settings that con...
79,Machine Learning Lifecycle,Process Step,Model Evaluation,Process of measuring how well a trained model ...
80,Machine Learning Lifecycle,Process Step,Validation,Validation is the process of assessing model p...
81,Machine Learning Lifecycle,Process Step,Model Interpretability,NaN
82,Machine Learning Lifecycle,Process Step,Deployment,Deployment is the process of integrating the t...
83,Machine Learning Lifecycle,Process Step,Monitoring,Ongoing process of tracking model performance ...
84,Machine Learning Lifecycle,Process Step,"Bias, Fairness, and Ethics",This step examines whether the model produces ...
18,Problem Definition,Process Step,Baseline Metrics (Current State),Quantify the current state of the problem usin...
15,Problem Definition,Process Step,Current State Analysis,"Describes how the process, system, or situatio..."
14,Problem Definition,Process Step,Desired State Metrics,Describe the target outcomes or performance le...
17,Problem Definition,Process Step,Historical Overview,"Summarizes what actions, initiatives, or attem..."
16,Problem Definition,Process Step,Root Cause Assessment,Identifies the underlying reasons why the prob...
49,Problem Solving Framework,Process Step,Goal Setting,"Thought process utilized to establish a clear,..."
50,Problem Solving Framework,Process Step,Problem Definition,"A Clear, Concise and explicit definition of th..."
144,Problem Solving Framework,Process Step,Problem Definition,Desired State Metrics: Describe the target out...
146,Problem Solving Framework,Process Step,Problem Definition,Current State Analysis: Describes how the proc...
148,Problem Solving Framework,Process Step,Problem Definition,Root Cause Assessment: Identifies the underlyi...
150,Problem Solving Framework,Process Step,Problem Definition,"Historical Overview: Summarizes what actions, ..."
152,Problem Solving Framework,Process Step,Problem Definition,Baseline Metrics (Current State): Quantify the...
51,Problem Solving Framework,Process Step,Current State Assessment,NaN
52,Problem Solving Framework,Process Step,Data Collection,"Data collection involves identifying, sourcing..."
53,Problem Solving Framework,Process Step,Root Cause Analysis,NaN
54,Problem Solving Framework,Process Step,Research and Exploration,NaN
55,Problem Solving Framework,Process Step,Option Generation,NaN
56,Problem Solving Framework,Process Step,Solution Design,NaN
57,Problem Solving Framework,Process Step,Feasibility Assessment,NaN
58,Problem Solving Framework,Process Step,Prioritization and Decision Making,NaN
59,Problem Solving Framework,Process Step,Implementation Planning,NaN
60,Problem Solving Framework,Process Step,Execution,NaN
61,Problem Solving Framework,Process Step,Testing and Validation,NaN
62,Problem Solving Framework,Process Step,Evaluation,NaN
63,Problem Solving Framework,Process Step,Optimization,NaN
64,Problem Solving Framework,Process Step,Documentation and Knowledge Sharing,NaN
65,Problem Solving Framework,Process Step,Monitoring,Ongoing process of tracking model performance ...
66,Problem Solving Framework,Process Step,Continuous Improvement,NaN
67,Problem Solving Framework,Process Step,"Governance, Risk, and Ethics",NaN

In [ ]:
from daily_processes import daily_test
daily_test()

In [ ]:
# Generate Python File Including All Dictionaries

from dict_processing import dict_defitions_dot_py
dict_defitions_dot_py()