In [ ]:
## MAKE NOTES ABOUT KNOWLEDGE BASE. 
# SPECIFICALLY IF I PROCESS NOT GENERAL DEFINITION IT WILL BE BROUGHT OVER. 
# General Definition it will only include if already Included

In [ ]:
# Change the Length of the Columns in the Dashboard.
# Filtering Order for Processes and Categorization is not great for anything that isn't a Formal PRocess with Process steps.
# Should be able to add an additional layer, so when there is #NA in orignal columns it still works.

#  Build a process for Specific Types of ML Procesess, Clustering to incorporate additional features into process - Convoluted as normal step.

In [1]:
import pandas as pd
import numpy as np
import sys

sys.path.append("/Users/derekdewald/Documents/Python/Github_Repo/d_py_functions")

In [8]:
from daily_etl_folder_mgmt import generate_files_for_streamlit

knowledge_base_df,process_df,consolidated_df = generate_files_for_streamlit()

In [10]:
consolidated_df['Process'].value_counts()

Process
Machine Learning Lifecycle    47
Behavioural Economics         20
Feature Selection             12
Communication                 10
Cardinal Presentation Sins     9
General Definition             6
Goal Setting                   6
Model Selection                6
Data Collection                5
Data Preparation               5
Bias, Fairness, and Ethics     4
Regularization                 3
Model Evaluation               2
Deployment                     1
Exploratory Data Analysis      1
Feature Engineering            1
Hyperparameter Tuning          1
Model Interpretability         1
Monitoring                     1
Organization - Definition      1
Problem Definition             1
Training                       1
Validation                     1
Name: count, dtype: int64

In [4]:
consolidated_df[consolidated_df['Process']=='Communication']

,Process,Categorization,Word,Definition
93,Communication,Process Step,Understand Your Message,
94,Communication,Process Step,Understand Your Audience,
95,Communication,Process Step,Understand Your Strategy,"Beyond understanding Your Message, you need to..."
96,Communication,Process Step,Choosing a Medium,"While not always give a choice, it is importan..."
97,Communication,Process Step,Understand Your Visuals,
98,Communication,Process Step,Message Spareness,"Utilize a less is more approach, whether that ..."
99,Communication,Process Step,Re-enforce the Message,
100,Communication,Process Step,Cardinal Communication Sins,
101,Communication,Process Step,General Expectations,
102,Communication,Process Step,Measuing Effectiveness,How can one measure how effective/ineffective ...

In [6]:
consolidated_df[consolidated_df['Process']=='Machine Learning Lifecycle']

,Process,Categorization,Word,Definition
17,Machine Learning Lifecycle,Process,Definition,To Be Defined
46,Machine Learning Lifecycle,Process Step,Goal Setting,"Thought process utilized to establish a clear,..."
112,Machine Learning Lifecycle,Goal Setting,Specific,Describes what will be accomplished and what s...
113,Machine Learning Lifecycle,Goal Setting,Measurable,Includes a clear way to track progress or dete...
114,Machine Learning Lifecycle,Goal Setting,Achievable,"Realistic given available time, resources, ski..."
115,Machine Learning Lifecycle,Goal Setting,Relevant,"Aligns with broader priorities, such as team o..."
116,Machine Learning Lifecycle,Goal Setting,Time Bound,Includes a clear deadline or timeframe for com...
47,Machine Learning Lifecycle,Process Step,Problem Definition,"A Clear, Concise and explicit definition of th..."
48,Machine Learning Lifecycle,Process Step,Data Collection,"Data collection involves identifying, sourcing..."
126,Machine Learning Lifecycle,Data Collection,Label Data,"Ensure that All data is defined, and classifie..."
127,Machine Learning Lifecycle,Data Collection,Ensure Sufficient Data Exists,Ensure that model has sufficient representatio...
128,Machine Learning Lifecycle,Data Collection,Challenges from Missing Data,What concessions have we made due to a lack of...
129,Machine Learning Lifecycle,Data Collection,Who Owns the Data,"Who is the Data Steward, and Process owners? A..."
49,Machine Learning Lifecycle,Process Step,Data Preparation,Data preparation focuses on cleaning and struc...
122,Machine Learning Lifecycle,Data Preparation,Regularization,Explain what this means from a practical appli...
50,Machine Learning Lifecycle,Process Step,Exploratory Data Analysis,Foundational step in ensuring the success of a...
51,Machine Learning Lifecycle,Process Step,Feature Engineering,Process of creating new input variables that b...
52,Machine Learning Lifecycle,Process Step,Feature Selection,Process of identifying and retaining the most ...
134,Machine Learning Lifecycle,Feature Selection,Explain Feature Practical Relevance,Generate feature importance or explanation out...
135,Machine Learning Lifecycle,Feature Selection,Remove Unnecessary Features,Remove features with high missingness or low v...
136,Machine Learning Lifecycle,Feature Selection,Understand Feature Correlations,Check for multicollinearity or redundant featu...
137,Machine Learning Lifecycle,Feature Selection,Document Feature Statistical Relevance,Validate selected features using model or stat...
138,Machine Learning Lifecycle,Feature Selection,Avoid Ambguity,"Avoid ambiguous features. Is a Banana ripe, wh..."
139,Machine Learning Lifecycle,Feature Selection,Is a feature Random?,Careful when something is truly random generat...
140,Machine Learning Lifecycle,Feature Selection,Model Robustness,How robust is your model to change and what is...
141,Machine Learning Lifecycle,Feature Selection,Test Individual Feature Importance,Need to understand how much an individual feat...
142,Machine Learning Lifecycle,Feature Selection,Reconstruction Error in Autoencoders,Does this feature improve the model’s ability ...
143,Machine Learning Lifecycle,Feature Selection,Mutual Information with Latent Cluster Assignment,\nHow strongly is this feature associated with...
144,Machine Learning Lifecycle,Feature Selection,Permutation for Clustering,Permutation importance measures the value of a...
53,Machine Learning Lifecycle,Process Step,Model Selection,The process of choosing the most appropriate a...
120,Machine Learning Lifecycle,Model Selection,Define Baseline,
130,Machine Learning Lifecycle,Model Selection,Document Results and Choice,Ensure that final selection is documented and ...
131,Machine Learning Lifecycle,Model Selection,Define Validation Approach in Advance,Use cross-validation or a structured validatio...
132,Machine Learning Lifecycle,Model Selection,Validate no Leakage,Ensure no data leakage between training and va...
133,Machine Learning Lifecycle,Model Selection,Validate consistency over time,Confirm performance stability across folds or ...
54,Machine Learning Lifecycle,Process Step,Training,Process of fitting a machine learning model to...
55,Machine Learning Lifecycle,Process Step,Hyperparameter Tuning,Optimizing the configuration settings that con...
56,Machine Learning Lifecycle,Process Step,Model Evaluation,Process of measuring how well a trained model ...
121,Machine Learning Lifecycle,Model Evaluation,Test Relative to Baseline,
57,Machine Learning Lifecycle,Process Step,Validation,Validation is the process of assessing model p...
58,Machine Learning Lifecycle,Process Step,Model Interpretability,Process of explaining how a model makes predic...
59,Machine Learning Lifecycle,Process Step,Deployment,Deployment is the process of integrating the t...
60,Machine Learning Lifecycle,Process Step,Monitoring,Ongoing process of tracking model performance ...
61,Machine Learning Lifecycle,Process Step,"Bias, Fairness, and Ethics",This step examines whether the model produces ...
123,Machine Learning Lifecycle,"Bias, Fairness, and Ethics",Review Demographics,Evaluate model performance across key demograp...
124,Machine Learning Lifecycle,"Bias, Fairness, and Ethics",Test unitended discrimination,Review sensitive features and proxy variables....
125,Machine Learning Lifecycle,"Bias, Fairness, and Ethics",Document Fairness Checks,Document fairness checks and mitigation steps....

In [3]:
#from daily_etl_folder_mgmt import ETL
#ETL()

python_function_list Saved to /Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/
python_function_parameters Saved to /Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/

In [3]:
from objects_automated import object_dict

links = pd.read_csv(object_dict['csv_links']['python_object']['d_links'])
notes = pd.read_csv(object_dict['csv_links']['python_object']['google_notes_csv'])
definitions = pd.read_csv(object_dict['csv_links']['python_object']['google_definition_csv'])
technical_notes = pd.read_csv(object_dict['csv_links']['python_object']['technical_notes'])

In [10]:
from daily_etl_folder_mgmt import extract_object_dot_py
from objects_automated import object_dict as object_dict_auto
from objects_manual import object_dict as object_dict_man

extract_object_dot_py(object_dict_man,'/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/object_manual_published.xlsx')
extract_object_dot_py(object_dict_auto,'/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/object_auto_published.xlsx')

In [3]:
from daily_etl_folder_mgmt import generate_objects_automated_py
generate_objects_automated_py()

In [10]:
consolidated_xlsx = '/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/consolidated_dataset.xlsx'
consolidated_df = pd.read_excel(consolidated_xlsx)

In [11]:
consolidated_df[consolidated_df['Process']=='Algorithm Classification']

,Process,Categorization,Word,Definition,Location
120,Algorithm Classification,Definition,Anomaly Detection,Algorithm which designed to identify observati...,Definitions
121,Algorithm Classification,Definition,Classification,Algorithm which assign observations to one of ...,Definitions
122,Algorithm Classification,Definition,Clustering,Algorithm which group observations into cluste...,Definitions
123,Algorithm Classification,Definition,Regression,Algorithm which predict continuous numerical v...,Definitions
124,Algorithm Classification,Definition,Ranking / Recommendation,Algorithm which order items or suggest relevan...,Definitions
125,Algorithm Classification,Definition,Density Estimation,Approaches which involve modeling the underlyi...,Definitions
126,Algorithm Classification,Definition,Dimensionality Reduction,Algorithm which reduce the number of variables...,Definitions
127,Algorithm Classification,Definition,Feature Selection,Methods that identify and retain a subset of e...,Definitions
128,Algorithm Classification,Definition,Feature Transformation,Methods which modify existing features into ne...,Definitions
129,Algorithm Classification,Definition,Information Retrieval,NaN,Definitions
130,Algorithm Classification,Definition,Time Series Forecasting,NaN,Definitions
131,Algorithm Classification,Definition,Generative Models,NaN,Definitions
132,Algorithm Classification,Definition,Reinforcement Learning,NaN,Definitions
133,Algorithm Classification,Definition,Optimization,NaN,Definitions
134,Algorithm Classification,Definition,Graph Algorithms,NaN,Definitions
135,Algorithm Classification,Definition,Prediction,NaN,Definitions

In [ ]:
from daily_processes import daily_test
daily_test()

In [ ]:
# Generate Python File Including All Dictionaries

from dict_processing import dict_defitions_dot_py
dict_defitions_dot_py()