In [1]:
import pandas as pd
import numpy as np
import sys
sys.path.append("/Users/derekdewald/Documents/Python/Github_Repo/d_py_functions")

In [2]:
import os
os.getcwd()
os.listdir('/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data')

['.DS_Store',
 'consolidated_dataset.xlsx',
 'knowledge_base.xlsx',
 'object_auto_published.xlsx',
 'object_manual_published.xlsx']

In [ ]:
# Want to Bring Functions which Pull .py script into New Environment, so I can consistently Name Functions.
# I want to also Automate Definitions for Classification and Process.D


# How to Document Where A File/Table is Being Made or that a File Exists????


# How do I want test when I make a change?

In [6]:
df = pd.read_excel('/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/consolidated_dataset.xlsx')
df

,Process,Categorization,Word,Definition,Location
0,Behavioural Economics,Information,What Meaning Does a KPI actually have?,Before we figure out whether nurses have had a...,Notes
1,Behavioural Economics,Information,Organizations,Great at solving Problems. Bad at diagnosing ...,Notes
2,Behavioural Economics,Information,Think about the Medium,"Weekly, daily, hourly—the metronome of the new...",Notes
3,Behavioural Economics,Information,Unintended Consequences KPIs,Must consider what adverse effects one might c...,Notes
4,Feature Engineering,Guidance,Ratios or Observed Values,What ratios or proportions could better repres...,Notes
...,...,...,...,...,...
365,Data Dictionary,Column List,METRIC,NaN,Manual Objects
366,Data Dictionary,Column List,NOTES,NaN,Manual Objects
367,Data Dictionary,Column List,RECORD_TYPE,NaN,Manual Objects
368,Data Dictionary,Column List,UPDATE_DATE,NaN,Manual Objects
369,Data Dictionary,Definition,General Definition,List of Default Columns Used in Data Dictionary,Manual Objects

In [15]:
df[df['Categorization']=='Process Step']

,Process,Categorization,Word,Definition,Location
14,Problem Definition,Process Step,Desired State Metrics,Describe the target outcomes or performance le...,Notes
15,Problem Definition,Process Step,Current State Analysis,"Describes how the process, system, or situatio...",Notes
16,Problem Definition,Process Step,Root Cause Assessment,Identifies the underlying reasons why the prob...,Notes
17,Problem Definition,Process Step,Historical Overview,"Summarizes what actions, initiatives, or attem...",Notes
18,Problem Definition,Process Step,Baseline Metrics (Current State),Quantify the current state of the problem usin...,Notes
...,...,...,...,...,...
353,Machine Learning Lifecycle,Process Step,Validation,NaN,Manual Objects
354,Machine Learning Lifecycle,Process Step,Model Interpretability,NaN,Manual Objects
355,Machine Learning Lifecycle,Process Step,Deployment,NaN,Manual Objects
356,Machine Learning Lifecycle,Process Step,Monitoring,NaN,Manual Objects
357,Machine Learning Lifecycle,Process Step,"Bias, Fairness, and Ethics",NaN,Manual Objects

In [16]:
# Create Total
final_df = df.groupby(['Process','Categorization']).size().reset_index().rename(columns={0:'Record Count'})
final_df['File Source'] = 'Total'
# final_df = pd.concat([
#     final_df,
#     df.groupby(['Process','Categorization','Location']).size().reset_index().rename(columns={0:'Record Count'}).rename(columns={'Location':'File Source'})
# ])
final_df

,Process,Categorization,Record Count,File Source
0,Behavioural Economics,Concept,28,Total
1,Behavioural Economics,Information,12,Total
2,Best Linear Unbiased Estimator,Definition,2,Total
3,Best Linear Unbiased Estimator,Required,8,Total
4,Categorization Values Currently in Use,Definition,1,Total
5,Categorization Values Currently in Use,Reference List,13,Total
6,Data Collection,Guidance,6,Total
7,Data Dictionary,Column List,20,Total
8,Data Dictionary,Definition,2,Total
9,Data Preparation,Definition,16,Total
10,Data Preparation,Regularization,10,Total
11,Data Preparation,Transformation,6,Total
12,Documentation,Definition,2,Total
13,Documentation,Reference List,14,Total
14,Feature Engineering,Guidance,6,Total
15,General Definition,Process Step,17,Total
16,Goal Setting,Requirement,10,Total
17,Machine Learning Lifecycle,Definition,10,Total
18,Machine Learning Lifecycle,Feature Selection,4,Total
19,Machine Learning Lifecycle,Guidance,10,Total
20,Machine Learning Lifecycle,Process Step,37,Total
21,Machine Learning Lifecycle,Regularization,5,Total
22,Machine Learning Lifecycle,Requirement,5,Total
23,Machine Learning Lifecycle,Transformation,3,Total
24,Model Evaluation,Feature Selection,8,Total
25,Notes,Definition,2,Total
26,Notes,Filter Order,18,Total
27,Problem Definition,Guidance,8,Total
28,Problem Definition,Process Step,10,Total
29,Problem Solving Framework,Definition,2,Total
30,Problem Solving Framework,Guidance,7,Total
31,Problem Solving Framework,Process Step,43,Total
32,Problem Solving Framework,Requirement,5,Total
33,Process Values Currently in Use,Definition,1,Total
34,Process Values Currently in Use,Reference List,15,Total
35,Statistics,Definition,4,Total