In [153]:
%history -f text.txt

In [ ]:
# NEED TO CREATE A DOCUMENTATION STANDARD.
# NEED TO CREATE A SAVING STANDARD
# NEED TO CREATE A TESTING STANDARD.

In [ ]:
## USE PROCESS: CATEGORIZATION. CATEGFORIATION: DEFINITION WORD: Metric as an example.
# How to get Optimization and Loss Functions.
# Update ML to have all Parameters?
# Process >> Process Step >> __________
# I do not want to Bring Automated. It's confusing and causes Duplication. 
# I want to insure that Every Process from Definition Is Included.

# I should be able to Manage Everything from Notes.

# Process.
# Categorization - All Process Steps should be retained in Definition. Along with an Explanation as to what that process is.
# Word
# Definition. 

# Everything Should Have a Master Process.

In [1]:
import pandas as pd
import numpy as np
import datetime

import sys
sys.path.append("/Users/derekdewald/Documents/Python/Github_Repo/d_py_functions")

from objects_automated import object_dict

### Local Files

In [2]:
consolidated_df = pd.read_excel('/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/consolidated_dataset.xlsx')
knowledge_base_df = pd.read_excel('/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/knowledge_base.xlsx')

### Google Sheets

In [2]:
link_df = pd.read_csv(object_dict['csv_links']['python_object']['d_links'])
notes_df = pd.read_csv(object_dict['csv_links']['python_object']['google_notes_csv'])
definition_df = pd.read_csv(object_dict['csv_links']['python_object']['google_definition_csv'])
technical_notes = pd.read_csv(object_dict['csv_links']['python_object']['technical_notes'])

In [26]:
from daily_etl_folder_mgmt import generate_files_for_streamlit
knowledge_base_df,process_df,consolidated_df = generate_files_for_streamlit(definition_df,notes_df)

## Review Topic

In [62]:
notes_df = pd.read_csv(object_dict['csv_links']['python_object']['google_notes_csv'])
definition_df = pd.read_csv(object_dict['csv_links']['python_object']['google_definition_csv'])

In [198]:

#consolidated_df = generate_files_for_streamlit(definition_df,notes_df)
knowledge_base_df,process_df,consolidated_df = generate_files_for_streamlit(definition_df,notes_df)
#consolidated_df[consolidated_df['Process']=='Communication']

In [199]:
consolidated_df[consolidated_df['Word']=='Regularization']

,Process,Categorization,Word,Definition
70,Data Preparation,Process Step,Regularization,Explain what this means from a practical appli...
117,Machine Learning Lifecycle,Data Preparation,Regularization,Explain what this means from a practical appli...

In [200]:
consolidated_df[consolidated_df['Process']=='Data Preparation']

,Process,Categorization,Word,Definition
69,Data Preparation,Process,Definition,Data preparation focuses on cleaning and struc...
70,Data Preparation,Process Step,Regularization,Explain what this means from a practical appli...
71,Data Preparation,Regularization,ElasticNet,Approach which combines L1 and L2 Regularization.
72,Data Preparation,Regularization,Lasso,Technique used to prevent overfitting by addin...
73,Data Preparation,Regularization,Ridge,Technique used to prevent overfitting by addin...

In [201]:
consolidated_df[consolidated_df['Process']=='Machine Learning Lifecycle']

,Process,Categorization,Word,Definition
103,Machine Learning Lifecycle,Process,Definition,To Be Defined
104,Machine Learning Lifecycle,Process Step,Goal Setting,"Thought process utilized to establish a clear,..."
105,Machine Learning Lifecycle,Goal Setting,Specific,Describes what will be accomplished and what s...
106,Machine Learning Lifecycle,Goal Setting,Measurable,Includes a clear way to track progress or dete...
107,Machine Learning Lifecycle,Goal Setting,Achievable,"Realistic given available time, resources, ski..."
108,Machine Learning Lifecycle,Goal Setting,Relevant,"Aligns with broader priorities, such as team o..."
109,Machine Learning Lifecycle,Goal Setting,Time Bound,Includes a clear deadline or timeframe for com...
110,Machine Learning Lifecycle,Process Step,Problem Definition,"A Clear, Concise and explicit definition of th..."
111,Machine Learning Lifecycle,Process Step,Data Collection,"Data collection involves identifying, sourcing..."
112,Machine Learning Lifecycle,Data Collection,Label Data,"Ensure that All data is defined, and classifie..."
113,Machine Learning Lifecycle,Data Collection,Ensure Sufficient Data Exists,Ensure that model has sufficient representatio...
114,Machine Learning Lifecycle,Data Collection,Challenges from Missing Data,What concessions have we made due to a lack of...
115,Machine Learning Lifecycle,Data Collection,Who Owns the Data,"Who is the Data Steward, and Process owners? A..."
116,Machine Learning Lifecycle,Process Step,Data Preparation,Data preparation focuses on cleaning and struc...
117,Machine Learning Lifecycle,Data Preparation,Regularization,Explain what this means from a practical appli...
0,Machine Learning Lifecycle,Regularization,ElasticNet,Approach which combines L1 and L2 Regularization.
1,Machine Learning Lifecycle,Regularization,Lasso,Technique used to prevent overfitting by addin...
2,Machine Learning Lifecycle,Regularization,Ridge,Technique used to prevent overfitting by addin...
118,Machine Learning Lifecycle,Process Step,Exploratory Data Analysis,Foundational step in ensuring the success of a...
119,Machine Learning Lifecycle,Process Step,Feature Engineering,Process of creating new input variables that b...
120,Machine Learning Lifecycle,Process Step,Feature Selection,Process of identifying and retaining the most ...
121,Machine Learning Lifecycle,Feature Selection,Explain Feature Practical Relevance,Generate feature importance or explanation out...
122,Machine Learning Lifecycle,Feature Selection,Remove Unnecessary Features,Remove features with high missingness or low v...
123,Machine Learning Lifecycle,Feature Selection,Understand Feature Correlations,Check for multicollinearity or redundant featu...
124,Machine Learning Lifecycle,Feature Selection,Document Feature Statistical Relevance,Validate selected features using model or stat...
125,Machine Learning Lifecycle,Feature Selection,Avoid Ambguity,"Avoid ambiguous features. Is a Banana ripe, wh..."
126,Machine Learning Lifecycle,Feature Selection,Is a feature Random?,Careful when something is truly random generat...
127,Machine Learning Lifecycle,Feature Selection,Model Robustness,How robust is your model to change and what is...
128,Machine Learning Lifecycle,Feature Selection,Test Individual Feature Importance,Need to understand how much an individual feat...
129,Machine Learning Lifecycle,Feature Selection,Reconstruction Error in Autoencoders,Does this feature improve the model’s ability ...
130,Machine Learning Lifecycle,Feature Selection,Mutual Information with Latent Cluster Assignment,How strongly is this feature associated with t...
131,Machine Learning Lifecycle,Feature Selection,Permutation for Clustering,Permutation importance measures the value of a...
132,Machine Learning Lifecycle,Process Step,Model Selection,The process of choosing the most appropriate a...
133,Machine Learning Lifecycle,Model Selection,Define Baseline,
134,Machine Learning Lifecycle,Model Selection,Document Results and Choice,Ensure that final selection is documented and ...
135,Machine Learning Lifecycle,Model Selection,Define Validation Approach in Advance,Use cross-validation or a structured validatio...
136,Machine Learning Lifecycle,Model Selection,Validate no Leakage,Ensure no data leakage between training and va...
137,Machine Learning Lifecycle,Model Selection,Validate consistency over time,Confirm performance stability across folds or ...
138,Machine Learning Lifecycle,Process Step,Training,Process of fitting a machine learning model to...
139,Machine Learning Lifecycle,Process Step,Hyperparameter Tuning,Optimizing the configuration settings that con...
140,Machine Learning Lifecycle,Process Step,Model Evaluation,Process of measuring how well a trained model ...
141,Machine Learning Lifecycle,Model Evaluation,Test Relative to Baseline,
142,Machine Learning Lifecycle,Process Step,Validation,Validation is the process of assessing model p...
143,Machine Learning Lifecycle,Process Step,Model Interpretability,Process of explaining how a model makes predic...
144,Machine Learning Lifecycle,Process Step,Deployment,Deployment is the process of integrating the t...
145,Machine Learning Lifecycle,Process Step,Monitoring,Ongoing process of tracking model performance ...
146,Machine Learning Lifecycle,Process Step,"Bias, Fairness, and Ethics",This step examines whether the model produces ...
147,Machine Learning Lifecycle,"Bias, Fairness, and Ethics",Review Demographics,Evaluate model performance across key demograp...
148,Machine Learning Lifecycle,"Bias, Fairness, and Ethics",Test unitended discrimination,Review sensitive features and proxy variables....
149,Machine Learning Lifecycle,"Bias, Fairness, and Ethics",Document Fairness Checks,Document fairness checks and mitigation steps....

In [96]:
consolidated_data[consolidated_data['Process']=='Data Preparation']

,Process,Categorization,Word,Definition
3,Data Preparation,Process,Definition,Data preparation focuses on cleaning and struc...
75,Data Preparation,Process Step,Regularization,Explain what this means from a practical appli...
137,Data Preparation,Regularization,ElasticNet,Approach which combines L1 and L2 Regularization.
138,Data Preparation,Regularization,Lasso,Technique used to prevent overfitting by addin...
139,Data Preparation,Regularization,Ridge,Technique used to prevent overfitting by addin...

In [203]:
consolidated_df[consolidated_df['Process']=='Communication']

,Process,Categorization,Word,Definition
44,Communication,Process,Definition,
45,Communication,Process Step,Understand Your Message,
46,Communication,Process Step,Understand Your Audience,
47,Communication,Process Step,Understand Your Strategy,"Beyond understanding Your Message, you need to..."
48,Communication,Process Step,Choosing a Medium,"While not always give a choice, it is importan..."
49,Communication,Process Step,Understand Your Visuals,
50,Communication,Process Step,Message Spareness,"Utilize a less is more approach, whether that ..."
51,Communication,Process Step,Re-enforce the Message,
52,Communication,Process Step,Cardinal Communication Sins,
53,Communication,Cardinal Communication Sins,Deliver Simplicity,Do not make the user think
54,Communication,Cardinal Communication Sins,Do Not Demand Recall,Do not make the user remember. If the Speaker ...
55,Communication,Cardinal Communication Sins,Visuals in 2D,Do not use 3D unless absolutely necessary.
56,Communication,Cardinal Communication Sins,Avoid Pie Charts,Pie Charts. They Suck.
57,Communication,Cardinal Communication Sins,Do Not Offend Your Audience,
58,Communication,Cardinal Communication Sins,Do Not Let Predjudices Close Your Mind,
59,Communication,Cardinal Communication Sins,Don’t waste the advantage that thought has ove...,
60,Communication,Cardinal Communication Sins,Hearing vs Listening,"Most were born hearing well, EVERYONE must lea..."
61,Communication,Cardinal Communication Sins,Always Thank Your Audience,
62,Communication,Process Step,General Expectations,
63,Communication,Process Step,Measuing Effectiveness,How can one measure how effective/ineffective ...

In [49]:
t[t['Definition_'].notnull()]

,Process,Categorization,Word,Definition,Definition_,Word_,NP_ORDER
117,Machine Learning Lifecycle,Data Preparation,Regularization,Explain what this means from a practical appli...,Approach which combines L1 and L2 Regularization.,ElasticNet,25.0
118,Machine Learning Lifecycle,Data Preparation,Regularization,Explain what this means from a practical appli...,Technique used to prevent overfitting by addin...,Lasso,26.0
119,Machine Learning Lifecycle,Data Preparation,Regularization,Explain what this means from a practical appli...,Technique used to prevent overfitting by addin...,Ridge,27.0

,Process,Categorization,Definition,Word_,NP_ORDER
0,Machine Learning Lifecycle,Goal Setting,Describes what will be accomplished and what s...,Specific,14
1,Machine Learning Lifecycle,Goal Setting,Includes a clear way to track progress or dete...,Measurable,15
2,Machine Learning Lifecycle,Goal Setting,"Realistic given available time, resources, ski...",Achievable,16
3,Machine Learning Lifecycle,Goal Setting,"Aligns with broader priorities, such as team o...",Relevant,17
4,Machine Learning Lifecycle,Goal Setting,Includes a clear deadline or timeframe for com...,Time Bound,18
5,Data Preparation,Regularization,Approach which combines L1 and L2 Regularization.,ElasticNet,25
6,Data Preparation,Regularization,Technique used to prevent overfitting by addin...,Lasso,26
7,Data Preparation,Regularization,Technique used to prevent overfitting by addin...,Ridge,27
8,Machine Learning Lifecycle,Model Selection,,Define Baseline,44
9,Machine Learning Lifecycle,Model Evaluation,,Test Relative to Baseline,45
10,Machine Learning Lifecycle,Data Preparation,Explain what this means from a practical appli...,Regularization,46
11,Machine Learning Lifecycle,"Bias, Fairness, and Ethics",Evaluate model performance across key demograp...,Review Demographics,53
12,Machine Learning Lifecycle,"Bias, Fairness, and Ethics",Review sensitive features and proxy variables....,Test unitended discrimination,54
13,Machine Learning Lifecycle,"Bias, Fairness, and Ethics",Document fairness checks and mitigation steps....,Document Fairness Checks,55
14,Machine Learning Lifecycle,Data Collection,"Ensure that All data is defined, and classifie...",Label Data,56
15,Machine Learning Lifecycle,Data Collection,Ensure that model has sufficient representatio...,Ensure Sufficient Data Exists,57
16,Machine Learning Lifecycle,Data Collection,What concessions have we made due to a lack of...,Challenges from Missing Data,58
17,Machine Learning Lifecycle,Data Collection,"Who is the Data Steward, and Process owners? A...",Who Owns the Data,59
18,Machine Learning Lifecycle,Model Selection,Ensure that final selection is documented and ...,Document Results and Choice,60
19,Machine Learning Lifecycle,Model Selection,Use cross-validation or a structured validatio...,Define Validation Approach in Advance,61
20,Machine Learning Lifecycle,Model Selection,Ensure no data leakage between training and va...,Validate no Leakage,62
21,Machine Learning Lifecycle,Model Selection,Confirm performance stability across folds or ...,Validate consistency over time,63
22,Machine Learning Lifecycle,Feature Selection,Generate feature importance or explanation out...,Explain Feature Practical Relevance,64
23,Machine Learning Lifecycle,Feature Selection,Remove features with high missingness or low v...,Remove Unnecessary Features,65
24,Machine Learning Lifecycle,Feature Selection,Check for multicollinearity or redundant featu...,Understand Feature Correlations,66
25,Machine Learning Lifecycle,Feature Selection,Validate selected features using model or stat...,Document Feature Statistical Relevance,67
26,Machine Learning Lifecycle,Feature Selection,"Avoid ambiguous features. Is a Banana ripe, wh...",Avoid Ambguity,68
27,Machine Learning Lifecycle,Feature Selection,Careful when something is truly random generat...,Is a feature Random?,69
28,Machine Learning Lifecycle,Feature Selection,How robust is your model to change and what is...,Model Robustness,70
29,Machine Learning Lifecycle,Feature Selection,Need to understand how much an individual feat...,Test Individual Feature Importance,71
30,Machine Learning Lifecycle,Feature Selection,Does this feature improve the model’s ability ...,Reconstruction Error in Autoencoders,72
31,Machine Learning Lifecycle,Feature Selection,How strongly is this feature associated with t...,Mutual Information with Latent Cluster Assignment,73
32,Machine Learning Lifecycle,Feature Selection,Permutation importance measures the value of a...,Permutation for Clustering,74
33,Communication,Cardinal Communication Sins,Do not make the user think,Deliver Simplicity,85
34,Communication,Cardinal Communication Sins,Do not make the user remember. If the Speaker ...,Do Not Demand Recall,86
35,Communication,Cardinal Communication Sins,Do not use 3D unless absolutely necessary.,Visuals in 2D,87
36,Communication,Cardinal Communication Sins,Pie Charts. They Suck.,Avoid Pie Charts,88
37,Communication,Cardinal Communication Sins,,Do Not Offend Your Audience,89
38,Communication,Cardinal Communication Sins,,Do Not Let Predjudices Close Your Mind,90
39,Communication,Cardinal Communication Sins,,Don’t waste the advantage that thought has ove...,91
40,Communication,Cardinal Communication Sins,"Most were born hearing well, EVERYONE must lea...",Hearing vs Listening,92
41,Communication,Cardinal Communication Sins,,Always Thank Your Audience,93

In [57]:
consolidated_df[consolidated_df['Process']=='Machine Learning Lifecycle']

,Process,Categorization,Word,Definition,NP_ORDER,Word_,PROC_ORDER,CAT_ORDER
17,Machine Learning Lifecycle,Process,Definition,To Be Defined,0.0,NaN,NaN,0
47,Machine Learning Lifecycle,Process Step,Goal Setting,"Thought process utilized to establish a clear,...",0.0,NaN,0.0,1
122,Machine Learning Lifecycle,Goal Setting,Specific,Describes what will be accomplished and what s...,14.0,Specific,0.0,1
123,Machine Learning Lifecycle,Goal Setting,Measurable,Includes a clear way to track progress or dete...,15.0,Measurable,0.0,1
124,Machine Learning Lifecycle,Goal Setting,Achievable,"Realistic given available time, resources, ski...",16.0,Achievable,0.0,1
125,Machine Learning Lifecycle,Goal Setting,Relevant,"Aligns with broader priorities, such as team o...",17.0,Relevant,0.0,1
126,Machine Learning Lifecycle,Goal Setting,Time Bound,Includes a clear deadline or timeframe for com...,18.0,Time Bound,0.0,1
48,Machine Learning Lifecycle,Process Step,Problem Definition,"A Clear, Concise and explicit definition of th...",0.0,NaN,1.0,1
49,Machine Learning Lifecycle,Process Step,Data Collection,"Data collection involves identifying, sourcing...",0.0,NaN,2.0,1
136,Machine Learning Lifecycle,Data Collection,Label Data,"Ensure that All data is defined, and classifie...",56.0,Label Data,2.0,1
137,Machine Learning Lifecycle,Data Collection,Ensure Sufficient Data Exists,Ensure that model has sufficient representatio...,57.0,Ensure Sufficient Data Exists,2.0,1
138,Machine Learning Lifecycle,Data Collection,Challenges from Missing Data,What concessions have we made due to a lack of...,58.0,Challenges from Missing Data,2.0,1
139,Machine Learning Lifecycle,Data Collection,Who Owns the Data,"Who is the Data Steward, and Process owners? A...",59.0,Who Owns the Data,2.0,1
50,Machine Learning Lifecycle,Process Step,Data Preparation,Data preparation focuses on cleaning and struc...,0.0,NaN,3.0,1
132,Machine Learning Lifecycle,Data Preparation,Regularization,Explain what this means from a practical appli...,46.0,Regularization,3.0,1
51,Machine Learning Lifecycle,Process Step,Exploratory Data Analysis,Foundational step in ensuring the success of a...,0.0,NaN,4.0,1
52,Machine Learning Lifecycle,Process Step,Feature Engineering,Process of creating new input variables that b...,0.0,NaN,5.0,1
53,Machine Learning Lifecycle,Process Step,Feature Selection,Process of identifying and retaining the most ...,0.0,NaN,6.0,1
144,Machine Learning Lifecycle,Feature Selection,Explain Feature Practical Relevance,Generate feature importance or explanation out...,64.0,Explain Feature Practical Relevance,6.0,1
145,Machine Learning Lifecycle,Feature Selection,Remove Unnecessary Features,Remove features with high missingness or low v...,65.0,Remove Unnecessary Features,6.0,1
146,Machine Learning Lifecycle,Feature Selection,Understand Feature Correlations,Check for multicollinearity or redundant featu...,66.0,Understand Feature Correlations,6.0,1
147,Machine Learning Lifecycle,Feature Selection,Document Feature Statistical Relevance,Validate selected features using model or stat...,67.0,Document Feature Statistical Relevance,6.0,1
148,Machine Learning Lifecycle,Feature Selection,Avoid Ambguity,"Avoid ambiguous features. Is a Banana ripe, wh...",68.0,Avoid Ambguity,6.0,1
149,Machine Learning Lifecycle,Feature Selection,Is a feature Random?,Careful when something is truly random generat...,69.0,Is a feature Random?,6.0,1
150,Machine Learning Lifecycle,Feature Selection,Model Robustness,How robust is your model to change and what is...,70.0,Model Robustness,6.0,1
151,Machine Learning Lifecycle,Feature Selection,Test Individual Feature Importance,Need to understand how much an individual feat...,71.0,Test Individual Feature Importance,6.0,1
152,Machine Learning Lifecycle,Feature Selection,Reconstruction Error in Autoencoders,Does this feature improve the model’s ability ...,72.0,Reconstruction Error in Autoencoders,6.0,1
153,Machine Learning Lifecycle,Feature Selection,Mutual Information with Latent Cluster Assignment,How strongly is this feature associated with t...,73.0,Mutual Information with Latent Cluster Assignment,6.0,1
154,Machine Learning Lifecycle,Feature Selection,Permutation for Clustering,Permutation importance measures the value of a...,74.0,Permutation for Clustering,6.0,1
54,Machine Learning Lifecycle,Process Step,Model Selection,The process of choosing the most appropriate a...,0.0,NaN,7.0,1
130,Machine Learning Lifecycle,Model Selection,Define Baseline,,44.0,Define Baseline,7.0,1
140,Machine Learning Lifecycle,Model Selection,Document Results and Choice,Ensure that final selection is documented and ...,60.0,Document Results and Choice,7.0,1
141,Machine Learning Lifecycle,Model Selection,Define Validation Approach in Advance,Use cross-validation or a structured validatio...,61.0,Define Validation Approach in Advance,7.0,1
142,Machine Learning Lifecycle,Model Selection,Validate no Leakage,Ensure no data leakage between training and va...,62.0,Validate no Leakage,7.0,1
143,Machine Learning Lifecycle,Model Selection,Validate consistency over time,Confirm performance stability across folds or ...,63.0,Validate consistency over time,7.0,1
55,Machine Learning Lifecycle,Process Step,Training,Process of fitting a machine learning model to...,0.0,NaN,8.0,1
56,Machine Learning Lifecycle,Process Step,Hyperparameter Tuning,Optimizing the configuration settings that con...,0.0,NaN,9.0,1
57,Machine Learning Lifecycle,Process Step,Model Evaluation,Process of measuring how well a trained model ...,0.0,NaN,10.0,1
131,Machine Learning Lifecycle,Model Evaluation,Test Relative to Baseline,,45.0,Test Relative to Baseline,10.0,1
58,Machine Learning Lifecycle,Process Step,Validation,Validation is the process of assessing model p...,0.0,NaN,11.0,1
59,Machine Learning Lifecycle,Process Step,Model Interpretability,Process of explaining how a model makes predic...,0.0,NaN,12.0,1
60,Machine Learning Lifecycle,Process Step,Deployment,Deployment is the process of integrating the t...,0.0,NaN,13.0,1
61,Machine Learning Lifecycle,Process Step,Monitoring,Ongoing process of tracking model performance ...,0.0,NaN,14.0,1
62,Machine Learning Lifecycle,Process Step,"Bias, Fairness, and Ethics",This step examines whether the model produces ...,0.0,NaN,15.0,1
133,Machine Learning Lifecycle,"Bias, Fairness, and Ethics",Review Demographics,Evaluate model performance across key demograp...,53.0,Review Demographics,15.0,1
134,Machine Learning Lifecycle,"Bias, Fairness, and Ethics",Test unitended discrimination,Review sensitive features and proxy variables....,54.0,Test unitended discrimination,15.0,1
135,Machine Learning Lifecycle,"Bias, Fairness, and Ethics",Document Fairness Checks,Document fairness checks and mitigation steps....,55.0,Document Fairness Checks,15.0,1