In [2]:
import pandas as pd
import numpy as np
import datetime

import sys
sys.path.append("/Users/derekdewald/Documents/Python/Github_Repo/d_py_functions")

In [3]:
from taxonomy_admin_functions import create_blank_function_doc_string

create_blank_function_doc_string()

Definition:
    TBD
Parameters:
    TBD
Returns:
    TBD
Date Created:
    28-Aug-26
Date Last Modified:
    28-Aug-26
Process:
    TBD
Categorization:
    TBD
Usage:
    TBD
Notes:
    None
Required Functions:
    None

In [131]:
from eda_functions import visualize_dataframe_in_notebook

df = pd.DataFrame(range(1,100),columns=['Key'])
df['Number'] = [np.random.choice(range(30,200)) for x in range(len(df))]*df['Key']
df['Currency'] = [np.random.choice([.25,.5,.75,.9]) for x in range(len(df))]*df['Number']
df['Currency1'] = df['Currency'].copy() 
df['Percent'] = [np.random.random()*100 for x in range(len(df))]

df.head()

   Key  Number  Currency  Currency1    Percent
0    1      66      49.5       49.5  18.662495
1    2     374     280.5      280.5  54.611216
2    3     144     129.6      129.6  22.105828
3    4     772     193.0      193.0  56.834327
4    5     850     425.0      425.0  70.515229

In [136]:
visualize_dataframe_in_notebook(
    df.head(),
    show_as_currency=['Currency'],
    show_as_currency_without_dec=['Currency1'],
    show_as_number=['Number'],
    show_as_percentage=['Percent']
)

## Daily Knowledge Base

In [4]:
from daily_etl_folder_mgmt import create_knowledge_base

knowledge_base_df= create_knowledge_base()

knowledge_base_df.head()

               Process Categorization        Word Definition          Source
0  Activation Function       Training  Leaky Relu             Knowledge Base
1  Activation Function       Training        Relu             Knowledge Base
2  Activation Function       Training     Sigmoid             Knowledge Base
3  Activation Function       Training     Softmax             Knowledge Base
4  Activation Function       Training        Tanh             Knowledge Base

## Documentation on Python Functions

In [3]:
from filesystem_tools import create_python_documentation

function_list,parameter_list = create_python_documentation()

python_function_list Saved to /Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/
python_function_parameters Saved to /Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/

In [6]:
function_list.head(2)

,Function,Definition,Parameters,Returns,Date Created,Date Last Modified,Process,Categorization,Usage,Notes,Folder
0,univariate_analysis,None,"[df, sparsity_threshold, skew_threshold, extre...",None,None,None,None,None,None,None,eda_functions.py
1,ml_validation_data_cleaning,None,[df],None,None,None,None,None,None,None,eda_functions.py

In [8]:
parameter_list.head(2)

              Function          Parameters Type Definition            Folder
0  univariate_analysis                  df                  eda_functions.py
1  univariate_analysis  sparsity_threshold                  eda_functions.py

In [4]:
from objects_automated import object_dict

notes = pd.read_csv(object_dict['csv_links']['python_object']['google_notes_csv'])
definitions = pd.read_csv(object_dict['csv_links']['python_object']['google_definition_csv'])

In [8]:
notes

,Process,Categorization,Word,Definition
0,Machine Learning Lifecycle,Process Step,Goal Setting,NaN
1,Machine Learning Lifecycle,Process Step,Problem Definition,NaN
2,Machine Learning Lifecycle,Process Step,Data Collection,NaN
3,Machine Learning Lifecycle,Process Step,Data Readiness,NaN
4,Machine Learning Lifecycle,Process Step,Data Preparation,NaN
...,...,...,...,...
260,Feature Representation Assessment,Taxonomy,Activation,Activation assesses whether an engineered feat...
261,Feature Representation Assessment,Taxonomy,Distinctiveness,Distinctiveness assesses whether an engineered...
262,Feature Representation Assessment,Taxonomy,Combination Coverage,Combination Coverage assesses how engineered f...
263,Feature Representation Assessment,Taxonomy,Conceptual Coverage,Conceptual Coverage assesses whether the engin...
264,Feature Representation Assessment,Taxonomy,Adequacy,Adequacy provides an overall assessment of whe...