In [3]:
import pandas as pd
import numpy as np
import sys

sys.path.append("/Users/derekdewald/Documents/Python/Github_Repo/d_py_functions")

In [ ]:

import pandas as pd
import numpy as np
import datetime
import shutil
import os
import ast
import re

from objects_manual import object_dict as object_dict_manual

In [5]:
links_df = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vTjXiFjpGgyqWDg9RImj1HR_BeriXs4c5-NSJVwQFn2eRKksitY46oJT0GvVX366LO-m1GM8znXDcBp/pub?gid=469651051&single=true&output=csv')

In [14]:
knowledge_base_df = pd.read_excel('/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/knowledge_base.xlsx')

'Machine Learning Ontology has been developed to support the learning, communication, and practical application of machine learning concepts, from foundational theory to real-world implementation. As the field continues to evolve rapidly in both scope and complexity, a clear and consistent framework is essential for organizing concepts, distinguishing related ideas, and translating theory into practice. The ontology is founded on three core principles and organized into five complementary dimensions, each describing a distinct aspect of machine learning knowledge. Together, these dimensions provide a structured framework for understanding, classifying, and communicating analytical concepts'

In [10]:
knowledge_base_df[knowledge_base_df['Process']=='ML Model Taxonomy']

Empty DataFrame
Columns: [Process, Categorization, Word, Definition, Source]
Index: []

In [ ]:
ml_model_tax_list = knowledge_base_df[knowledge_base_df['Process']=='Machine Learning Ontology']['Word'].tolist()

In [37]:
py_dict_required_columns = knowledge_base_df[knowledge_base_df['Process']=='Python String Documentation']['Word'].tolist()
py_dict_required_columns

['Definition',
 'Parameters',
 'Returns',
 'Date Created',
 'Date Last Modified',
 'Process',
 'Categorization',
 'Usage',
 'Notes',
 'Required Functions']

In [ ]:

object_dict['process_reference_list'] = {{
    'Process':"Documentation Taxonomy Categorization",
    'Categorization':'Reference List',
    'Word':"Documentation Taxonomy Process",
    'Definition':"Comprehensive List of all Values utilized in Organizational Taxonomy in the Column Process",
    'publish':1,
    'python_object':{process_list}
    }}

object_dict['cat_reference_list'] = {{
    'Process':"Documentation Taxonomy Categorization",
    'Categorization':'Reference List',
    'Word':"Documentation Taxonomy Categorization",
    'Definition':"Comprehensive List of all Values utilized in Organizational Taxonomy in the Column Categorization",
    'publish':1,
    'python_object':{cat_list}
    }}

object_dict['algo_class_ref_list'] = {{
    'Process':"Algorithm Categorization",
    'Categorization':'Reference List',
    'Word':"Algorithm Categorization Reference List",
    'Definition':"Comprehensive List of all Values utilized in Algorithm Categorization, used to Categorize ML Methods in Algorithm Taxonomy",
    'publish':0,
    'python_object':{algo_class_list}
    }}

object_dict['dot_py_reference_proc'] = {{
    'Process':"Dot Py String Taxonomy Process",
    'Categorization':'Reference List',
    'Word':"Dot Py String Taxonomy Process",
    'Definition':"Comprehensive List of all Values utilized in Organizational Taxonomy in the Column Process",
    'publish':1,
    'python_object':{dot_py_proc}
    }}

object_dict['dot_py_reference_cat'] = {{
    'Process':"Dot Py String Taxonomy Categorization",
    'Categorization':'Reference List',
    'Word':"Dot Py String Taxonomy Categorization",
    'Definition':"Comprehensive List of all Values utilized in Organizational Taxonomy in the Column Categorization",
    'publish':1,
    'python_object':{dot_py_cat}
    }}
    

        


object_dict['ml_method_list'] = {{
    'Process':"Method",
    'Categorization':'Reference List',
    'Word':"Method",
    'Definition':"List of Current Values for Distinct Types of Methods (While the distinction is subtle, and confusing), methods are of different types and to understand which to use, and when to apply, its important to understand the distinct classification",
    'publish':0,
    'python_object':{method_list}
        }}

object_dict['ml_function_list'] = {{
    'Process':"Function",
    'Categorization':'Reference List',
    'Word':"Function",
    'Definition':"List of Current Values for Functions. These methods refer to ML (not Python) as help to reinforce the nuance, subtly and what explicitly is happening when a ML model is running",
    'publish':0,
    'python_object':{func_list}
        }}

object_dict['ml_lp_list'] = {{
    'Process':"Learning Paradigm",
    'Categorization':'Reference List',
    'Word':"Learning Paradigm",
    'Definition':"List of Current Values for Items in ML Model Taxonomy",
    'publish':0,
    'python_object':{lp_list}
        }}

In [32]:
knowledge_base_df

,Process,Categorization,Word,Definition,Source
0,Activation Function,Training,Leaky Relu,NaN,Knowledge Base
1,Activation Function,Training,Relu,NaN,Knowledge Base
2,Activation Function,Training,Sigmoid,NaN,Knowledge Base
3,Activation Function,Training,Softmax,NaN,Knowledge Base
4,Activation Function,Training,Tanh,NaN,Knowledge Base
...,...,...,...,...,...
1677,Wicked Problem,Consideration,Every Solution Alters the Problem,Solving one part often creates or reveals new ...,Knowledge Base
1678,Wicked Problem,Consideration,No Enumerated Set of Solutions,There's no fixed list of possible solutions.,Knowledge Base
1679,Wicked Problem,Consideration,Every Wicked Problem Is Essentially Unique,"Even if it looks similar to another, the conte...",Knowledge Base
1680,Wicked Problem,Consideration,Every Wicked Problem Can Be Considered a Sympt...,It's often intertwined with or caused by other...,Knowledge Base
1681,Wicked Problem,Consideration,Stakeholders Have Conflicting Values,What’s “better” for one group may be “worse” f...,Knowledge Base

In [31]:
links_df

,Definition,COLUMN,Classification,Description,KEY,Link,CSV
0,Definitions,google_definition_csv,Google Sheet,"Repository of words, definition and base level...",NaN,https://docs.google.com/spreadsheets/d/1tZ-_5V...,https://docs.google.com/spreadsheets/d/e/2PACX...
1,Notes,google_notes_csv,Google Sheet,"Raw, Semi-Structured list of items which compr...",NaN,https://docs.google.com/spreadsheets/d/1jddkkF...,https://docs.google.com/spreadsheets/d/e/2PACX...
2,Words and Quotes,google_word_quote,NaN,Repository for Historical Words and Quotes of ...,NaN,NaN,https://docs.google.com/spreadsheets/d/e/2PACX...
3,Daily Activities,google_daily_activities,Google Sheet,Repository Tracking of Daily Activity results,NaN,NaN,https://docs.google.com/spreadsheets/d/e/2PACX...
4,Technical Notes,technical_notes,Google Sheet,"Notes Specifically related to Coding, Computer...",NaN,https://docs.google.com/spreadsheets/d/1FpYYq4...,https://docs.google.com/spreadsheets/d/e/2PACX...
5,Mapping Sheet,d_links,Google Sheet,THIS SHEET.,NaN,https://docs.google.com/spreadsheets/d/14CtNmN...,https://docs.google.com/spreadsheets/d/e/2PACX...
6,Python Functions,function_list_url,Git Hub,"Excel File of Python Functions, as generated f...",NaN,NaN,https://raw.githubusercontent.com/derek-dewald...
7,Python Function Parameters,parameter_list_url,Git Hub,NaN,NaN,NaN,https://raw.githubusercontent.com/derek-dewald...
8,Folder Table of Contents,folder_toc_url,NaN,NaN,NaN,NaN,https://raw.githubusercontent.com/derek-dewald...
9,Consolidated Notes,d_knowledge_base_url,NaN,NaN,NaN,NaN,https://raw.githubusercontent.com/derek-dewald...
10,Process Library,process_cl,NaN,NaN,NaN,NaN,https://raw.githubusercontent.com/derek-dewald...
11,Job Search,Job Search,Google Sheet,NaN,NaN,https://docs.google.com/spreadsheets/d/1sMdgmp...,NaN
12,OurWorldData,OurWorldData,Data,NaN,NaN,www.ourworlddata.org,NaN
13,KaggelDatasets,KaggelDatasets,Data,NaN,NaN,https://www.kaggle.com/datasets,NaN
14,StLouisFed,StLouisFed,Data,NaN,NaN,https://fred.stlouisfed.org,NaN
15,GoggleResearch,GoggleResearch,Data,NaN,NaN,https://datasetsearch.research.google.com,NaN
16,UCI,UCI,Data,NaN,NaN,https://archive.ics.uci.edu,NaN
17,AWS,AWS,Data,NaN,NaN,https://registry.opendata.aws/,NaN
18,AWSDataExchange,AWSDataExchange,Data,NaN,NaN,https://aws.amazon.com/data-exchange/,NaN
19,AWSPublicData,AWSPublicData,Data,NaN,NaN,https://aws.amazon.com/public-datasets/,NaN
20,SKlearn Model Parameters,SKlearn Model Parameters,Data,NaN,NaN,https://docs.google.com/spreadsheets/d/1GhIiuE...,https://docs.google.com/spreadsheets/d/e/2PACX...
21,Sklearn Models,Sklearn Models,Data,NaN,NaN,NaN,https://docs.google.com/spreadsheets/d/e/2PACX...
22,Consolidated Dashboard,Consolidated Dashboard,Data,NaN,NaN,NaN,NaN
23,TensorFlow Playground,TensorFlow Playground,External Site,Displaying How Tensor Flow Works.,NaN,https://playground.tensorflow.org/,NaN
24,SQL Cheatsheet,SQL Cheatsheet,NaN,NaN,NaN,https://raw.githubusercontent.com/derek-dewald...,NaN

In [26]:



        
    # Generate Information Required to Populate Automated Dot Py. 

    # Generate Lists for Consolidated Dataframe - Process and Categorization
    process_list = consolidated_df[consolidated_df['Process'].notnull()]['Process'].unique().tolist()
    process_list.sort()
    cat_list = consolidated_df[consolidated_df['Categorization'].notnull()]['Categorization'].unique().tolist()
    cat_list.sort()
   
    # Generate Definitions from definition_df
    algo_class_list = definition_df[(definition_df['Process']=='Algorithm Categorization')&(definition_df['Categorization']!='Process Step')]['Word'].unique().tolist()
    algo_class_list.sort()

    # Generate Lists for Dot Py String Dataframe - Process and Categorization
    dot_py_proc = dot_py_df[dot_py_df['Process'].notnull()]['Process'].unique().tolist()
    dot_py_cat = dot_py_df[dot_py_df['Categorization'].notnull()]['Categorization'].unique().tolist()
    
    
    method_list = definition_df[definition_df['Process']=='Method']['Word'].tolist()
    func_list = definition_df[definition_df['Process']=='Function']['Word'].tolist()
    lp_list = definition_df[definition_df['Process']=='Learning Paradigm']['Word'].tolist()
    
    # Generate df of CSV and URL
    csv_link_df = links_df[links_df['CSV'].notnull()]
    url_link_df = links_df[links_df['Link'].notnull()]










generate_objects_automated_py()

FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/consolidated_dataset.xlsx'

In [2]:
import pandas as pd
import numpy as np
import datetime

import sys
sys.path.append("/Users/derekdewald/Documents/Python/Github_Repo/d_py_functions")

In [ ]:
today = datetime.datetime.now().strftime('%d-%b-%y')

object_dict['template_doc_string'] = {
    'Process':"Organziation",
    'Categorization':'Reference String',
    'Word':"template_doc_string",
    'Definition':"Default Structure for Python Doc Strings",
    'publish':0,
    'python_object':f'''

    Definition:
        Definition of Function

    Parameters:
        List of Parameters

    Returns:
        Object Type

    date_created:{today}
    date_last_modified: {today}
    classification:TBD
    sub_classification:TBD
    usage:
        Example Function Call
'''
}

In [25]:
print(inspect.getsource(create_blank_function_doc_string))

def create_blank_function_doc_string(df=None):

    '''
    Definition:
        Function which generates Default Documentation for Python Function Documentaiton in consistent format.
    Parameters:
        df(dataframe): Knowledge base Dataframe. If None it will pull from either Local or Git Hub.
    Returns:
        str
    Date Created:
        28-Aug-26
    Date Last Modified:
        28-Aug-26
    Process:
        TBD
    Categorization:
        TBD
    Usage:
        create_blank_function_doc_string()
    Notes:
        None
    Required Functions:
        None


    '''
    if df ==None:
        try:
            df = pd.read_excel('/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/knowledge_base.xlsx')
        except:
            df = pd.read_excel("https://raw.githubusercontent.com/derek-dewald/Python_Tools/main/Streamlit/Data/knowledge_base.xlsx")

    parameters = df[df['Process']=='Python String Documentation']['Word'].tolist()

    text = ""
    #text = "\n".join( f"{item}:\n    TBD" for item in parameters)
    print(text)
    for item in parameters:
        if item in ['Date Created','Date Last Modified']:
            text += f"\n{item}:\n    {datetime.datetime.now().strftime('%d-%b-%y')}"
        elif item in ['Notes','Required Functions']:
            text += f"\n{item}:\n    None"

        else:
            text += f"\n{item}:\n    TBD"
    print(text)
    return df

In [23]:
import inspect
inspect(create_blank_function_doc_string)

TypeError: 'module' object is not callable

In [20]:



df = create_blank_function_doc_string()

Definition:
    TBD
Parameters:
    TBD
Returns:
    TBD
Date Created:
    28-Aug-26
Date Last Modified:
    28-Aug-26
Process:
    TBD
Categorization:
    TBD
Usage:
    TBD
Notes:
    None
Required Functions:
    None

In [ ]:

def gpt_question(list_,word_list=None):

    for word in list_:
        if not word_list:
            word_list = word
        else:
            word_list += f', {word}'
    text = f"""For the following words, can you please provide me for each word a definition which is 4-5 sentences highlighting the definition,\nits origin, its importance and application. If the word is a ML Model, can you also please define the following in point form,\ntype of ML learning, type of ML problem, size of data set it works best on, and anything else which might be appropriate.\nUnique Words: {word_list}
    """

    print(text)

## Document Pages:
# How I document things

# Machine Learning Code/ Projects
# Data Pipelines
# Career.
# Investing Guidelines



# Data Validation Process
# Data Exploration Process
# Synthetic Member Dataset
# Clustering ALog

# Data Dictionary
# Create LLM which can Answer Questions on my computer.
# Create LLM which is distributed to other computer.

In [ ]:
How can we effectively seek clarification on projects where ambiguity exists, how to escalate in instances where appropriate consideration has not been given or resources not ascribed or allocated. Example Questions who made this decision. Where is the supporting documentation, where decisions are made without appropriate inclusion, what are the repercussions and as a organization how do we prevent this from recoccuring..

In [ ]:

######################################
# Action Add DQ Item.
# Add Read Me, which Explanation of process and Definitions of all Categorizations.
# DQ Validation Component
# Question I need to ask Myself.
######################################

Migrate Away from @Shaw.ca

Loss - And all ways to measure
Optimization - and all ways to measure
Activation - And All Activation Functions.
How to select and use layers.
Metrics - Measure Model Performance
Cross Entropy. Binary and Categorical.

Design And Optimize Models
Automate Tasks 
Drive Innovation

# Establish Process to Set up a New Environment for Every Project. Use Poetry.


What did I learn from AWS.
WHat did I learn from Integration.

Goal | Measure of Success | Benefits | Challenges | Activities - Align to work log
RASCI = Understand how to reference discussion , integrate (Practically, Friendly, Realisitically) 
My Focus| Responsibility| Motivation | Clarification Required | 

- Training Doesn’t start (Loss doesn’t decrease)
- As you can literally train any data, there is something wrong if this occurs. Data Structure, Optimizer, Initial Weight, Learning Rate, Batch Size.
- Model Doesnt Beat Baseline
- Model Structure
- Can’t Severly Overfit despite trying.
- Increase Model Complexity and Size.
- If model is too complex, it can learn things that don’t exist, 
- L1 L2 Weight decay
Read Me? ?
WHAT IS THE PROCESS That this should be representing.


Speak, LORD, for Your servant is listening” (1 Samuel 3:9).
Indifference will keep in and ruin your life.
Unconfessed Sin follows you, and effects more than you.

In [ ]:
df[df['PRIMARY_ACTIVITY']==0][cols].groupby(columns).agg(
    ABS_TRAN_VAL = ('ABS_TRAN_AMT','sum'),
    NET_TRAN_VAL = ('TRANAMT','sum'),
    TXN_VOL = ('ABS_TRAN_AMT','count')
).reset_index()