In [1]:
import pandas as pd
import numpy as np
import datetime

import sys
sys.path.append("/Users/derekdewald/Documents/Python/Github_Repo/d_py_functions")

In [2]:
from daily_etl_folder_mgmt import generate_objects_automated_py

In [5]:
import os
os.listdir('/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/')

['.DS_Store',
 'knowledge_base.xlsx',
 'object_manual_published.xlsx',
 'consolidated_datset.xlsx']

In [6]:
knowledge_base_df = pd.read_excel('/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/consolidated_datset.xlsx')

In [ ]:
#poetry run streamlit run "/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Dashboard/D_Dashboard.py"

In [7]:
knowledge_base_df

,Process,Categorization,Word,Definition
0,Behavioural Economics,Information,Fact Believability,Facts about this epidemic that have lasted a f...
1,Behavioural Economics,Information,Facts Vs Statistics,More likely to die in accident in evening than...
2,Behavioural Economics,Information,Organizations,Great at solving Problems. Bad at diagnosing ...
3,Behavioural Economics,Information,Think about the Medium,"Weekly, daily, hourly—the metronome of the new..."
4,Behavioural Economics,Information,Unintended Consequences KPIs,Must consider what adverse effects one might c...
...,...,...,...,...
173,Problem Solving Framework,Process Step,Optimization,NaN
174,Problem Solving Framework,Process Step,Documentation and Knowledge Sharing,NaN
175,Problem Solving Framework,Process Step,Monitoring,Ongoing process of tracking model performance ...
176,Problem Solving Framework,Process Step,Continuous Improvement,NaN
177,Problem Solving Framework,Process Step,"Governance, Risk, and Ethics",NaN

In [8]:
knowledge_base_df[knowledge_base_df['Process']=='Best Linear Unbiased Estimator']

Empty DataFrame
Columns: [Process, Categorization, Word, Definition]
Index: []

In [57]:
knowledge_base_df['Process'].value_counts()

Process
Machine Learning Lifecycle        56
Problem Solving Framework         36
Behavioural Economics             20
Data Preparation                  16
Data Dictionary                   10
Notes                              9
Problem Definition                 9
Documentation                      7
Goal Setting                       5
Model Evaluation                   4
Data Collection                    3
Feature Engineering                3
Best Linear Unbiased Estimator     2
Name: count, dtype: int64

In [50]:
### WHEN DO I WANT TO RUN THIS, DEPENDS ON WHAT I CALL. If I run in process after generate_knowledgebase, then I dont need to recall everything.

In [51]:
df1 = df.groupby(['Process','Categorization','Location']).sum().reset_index()

In [52]:
df1[df1['Process']=='Best Linear Unbiased Estimator']

                           Process Categorization        Location  count
36  Best Linear Unbiased Estimator            All  knowledge_base      2
37  Best Linear Unbiased Estimator            All           notes      1
38  Best Linear Unbiased Estimator     Definition  knowledge_base      2
39  Best Linear Unbiased Estimator     Definition           notes      1

In [47]:
df1.head(40)

                           Process     Categorization          Location  count
0                              All               BLUE        definition      4
1                              All        Column List    knowledge_base     10
2                              All        Column List  manual_object_df     10
3                              All            Concept        definition     14
4                              All            Concept    knowledge_base     14
5                              All         Definition        definition      8
6                              All         Definition    knowledge_base     18
7                              All         Definition             notes      1
8                              All  Feature Selection        definition      4
9                              All  Feature Selection    knowledge_base      8
10                             All       Filter Order    knowledge_base      9
11                             All       Filter Order  manual_object_df      9
12                             All           Guidance    knowledge_base     27
13                             All           Guidance             notes     10
14                             All        Information    knowledge_base      6
15                             All        Information             notes      6
16                             All       Process Step        definition     17
17                             All       Process Step    knowledge_base     50
18                             All       Process Step  manual_object_df     35
19                             All       Process Step             notes      5
20                             All     Reference List    knowledge_base      7
21                             All     Reference List  manual_object_df      7
22                             All     Regularization        definition      5
23                             All     Regularization    knowledge_base     10
24                             All        Requirement    knowledge_base     15
25                             All        Requirement             notes      5
26                             All            Theorem        definition      1
27                             All     Transformation        definition      3
28                             All     Transformation    knowledge_base      6
29           Behavioural Economics                All        definition     14
30           Behavioural Economics                All    knowledge_base     20
31           Behavioural Economics                All             notes      6
32           Behavioural Economics            Concept        definition     14
33           Behavioural Economics            Concept    knowledge_base     14
34           Behavioural Economics        Information    knowledge_base      6
35           Behavioural Economics        Information             notes      6
36  Best Linear Unbiased Estimator                All    knowledge_base      2
37  Best Linear Unbiased Estimator                All             notes      1
38  Best Linear Unbiased Estimator         Definition    knowledge_base      2
39  Best Linear Unbiased Estimator         Definition             notes      1

In [3]:
d.groupby(['Process','Categorization']).size()

Process                         Categorization
Behavioural Economics           Concept              14
                                Information           6
Best Linear Unbiased Estimator  Definition            2
Data Collection                 Guidance              3
Data Dictionary                 Column List          10
Data Preparation                Definition            8
                                Regularization        5
                                Transformation        3
Documentation                   Reference List        7
Feature Engineering             Guidance              3
Goal Setting                    Requirement           5
Machine Learning Lifecycle      Definition            8
                                Feature Selection     4
                                Guidance             10
                                Process Step         21
                                Regularization        5
                                Requirement           5
                                Transformation        3
Model Evaluation                Feature Selection     4
Notes                           Filter Order          9
Problem Definition              Guidance              4
                                Process Step          5
Problem Solving Framework       Guidance              7
                                Process Step         24
                                Requirement           5
dtype: int64

In [8]:
d[d['Process']=='Best Linear Unbiased Estimator']

,Process,Categorization,Word,Definition
26,Best Linear Unbiased Estimator,Definition,Best Linear Unbiased Estimator,The Best Linear Unbiased Estimator (BLUE) is a...
159,Best Linear Unbiased Estimator,Definition,Best Linear Unbiased Estimator,Best Linear Unbiased Estimator:

In [28]:
d[d['Process']=='Machine Learning Lifecycle']

,Process,Categorization,Word,Definition
61,Machine Learning Lifecycle,Process Step,Goal Setting,"Thought process utilized to establish a clear,..."
118,Machine Learning Lifecycle,Requirement,Goal Setting,Specific: Describes what will be accomplished ...
120,Machine Learning Lifecycle,Requirement,Goal Setting,Measurable: Includes a clear way to track prog...
122,Machine Learning Lifecycle,Requirement,Goal Setting,"Achievable: Realistic given available time, re..."
124,Machine Learning Lifecycle,Requirement,Goal Setting,"Relevant: Aligns with broader priorities, such..."
126,Machine Learning Lifecycle,Requirement,Goal Setting,Time Bound: Includes a clear deadline or timef...
62,Machine Learning Lifecycle,Process Step,Problem Definition,"A Clear, Concise and explicit definition of th..."
128,Machine Learning Lifecycle,Process Step,Problem Definition,Desired State Metrics: Describe the target out...
130,Machine Learning Lifecycle,Process Step,Problem Definition,Current State Analysis: Describes how the proc...
132,Machine Learning Lifecycle,Process Step,Problem Definition,Root Cause Assessment: Identifies the underlyi...
134,Machine Learning Lifecycle,Process Step,Problem Definition,"Historical Overview: Summarizes what actions, ..."
136,Machine Learning Lifecycle,Process Step,Problem Definition,Baseline Metrics (Current State): Quantify the...
138,Machine Learning Lifecycle,Guidance,Problem Definition,Understand KPIs which are meaningful.: Attempt...
140,Machine Learning Lifecycle,Guidance,Problem Definition,What Lens is Problem Defined?: Must be careful...
142,Machine Learning Lifecycle,Guidance,Problem Definition,Stakeholder Investment?: How Invested are stak...
144,Machine Learning Lifecycle,Guidance,Problem Definition,Really Understand Problem Statement: Proceed w...
63,Machine Learning Lifecycle,Process Step,Data Collection,"Data collection involves identifying, sourcing..."
146,Machine Learning Lifecycle,Guidance,Data Collection,Challenges from Missing Data: What concessions...
148,Machine Learning Lifecycle,Guidance,Data Collection,"Who is the Steward: Who is the Data Steward, a..."
150,Machine Learning Lifecycle,Guidance,Data Collection,Review Definitions: Review Semantic and Functi...
151,Machine Learning Lifecycle,Definition,Data Preparation,Baseline: Baseline represents the typical or e...
152,Machine Learning Lifecycle,Definition,Data Preparation,Dimension: A Dimension is a conceptual axis of...
153,Machine Learning Lifecycle,Definition,Data Preparation,Implementation: An Implementation is a specifi...
154,Machine Learning Lifecycle,Definition,Data Preparation,Momentum: Momentum represents the direction an...
155,Machine Learning Lifecycle,Definition,Data Preparation,Parameter: A Parameter is a tuning choice that...
156,Machine Learning Lifecycle,Definition,Data Preparation,Volatility: Volatility represents the consiste...
162,Machine Learning Lifecycle,Definition,Data Preparation,Standardization: Standardization transforms da...
163,Machine Learning Lifecycle,Definition,Data Preparation,Regularization:
64,Machine Learning Lifecycle,Process Step,Data Preparation,Data preparation focuses on cleaning and struc...
157,Machine Learning Lifecycle,Regularization,Data Preparation,ElasticNet: Approach which combines L1 and L2 ...
158,Machine Learning Lifecycle,Regularization,Data Preparation,Lasso: Technique used to prevent overfitting b...
159,Machine Learning Lifecycle,Regularization,Data Preparation,Ridge: Technique used to prevent overfitting b...
160,Machine Learning Lifecycle,Regularization,Data Preparation,Imputation:
161,Machine Learning Lifecycle,Regularization,Data Preparation,Deletion:
65,Machine Learning Lifecycle,Process Step,Exploratory Data Analysis,Foundational step in ensuring the success of a...
66,Machine Learning Lifecycle,Process Step,Feature Engineering,Process of creating new input variables that b...
114,Machine Learning Lifecycle,Guidance,Feature Engineering,Ratios or Observed Values: What ratios or prop...
115,Machine Learning Lifecycle,Guidance,Feature Engineering,Include Interactions: What combinations or int...
116,Machine Learning Lifecycle,Guidance,Feature Engineering,How does Time Impact?: What time-based changes...
67,Machine Learning Lifecycle,Process Step,Feature Selection,Process of identifying and retaining the most ...
68,Machine Learning Lifecycle,Process Step,Model Selection,NaN
69,Machine Learning Lifecycle,Process Step,Training,Process of fitting a machine learning model to...
70,Machine Learning Lifecycle,Process Step,Hyperparameter Tuning,Optimizing the configuration settings that con...
71,Machine Learning Lifecycle,Process Step,Model Evaluation,Process of measuring how well a trained model ...
72,Machine Learning Lifecycle,Process Step,Validation,Validation is the process of assessing model p...
73,Machine Learning Lifecycle,Process Step,Model Interpretability,NaN
74,Machine Learning Lifecycle,Process Step,Deployment,Deployment is the process of integrating the t...
75,Machine Learning Lifecycle,Process Step,Monitoring,Ongoing process of tracking model performance ...
76,Machine Learning Lifecycle,Process Step,"Bias, Fairness, and Ethics",This step examines whether the model produces ...

In [6]:
d[d['Process']=='Problem Solving Framework']

,Process,Categorization,Word,Definition
42,Problem Solving Framework,Process Step,Goal Setting,"Thought process utilized to establish a clear,..."
104,Problem Solving Framework,Requirement,Goal Setting,Specific: Describes what will be accomplished ...
106,Problem Solving Framework,Requirement,Goal Setting,Measurable: Includes a clear way to track prog...
108,Problem Solving Framework,Requirement,Goal Setting,"Achievable: Realistic given available time, re..."
110,Problem Solving Framework,Requirement,Goal Setting,"Relevant: Aligns with broader priorities, such..."
112,Problem Solving Framework,Requirement,Goal Setting,Time Bound: Includes a clear deadline or timef...
43,Problem Solving Framework,Process Step,Problem Definition,"A Clear, Concise and explicit definition of th..."
114,Problem Solving Framework,Process Step,Problem Definition,Desired State Metrics: Describe the target out...
116,Problem Solving Framework,Process Step,Problem Definition,Current State Analysis: Describes how the proc...
118,Problem Solving Framework,Process Step,Problem Definition,Root Cause Assessment: Identifies the underlyi...
120,Problem Solving Framework,Process Step,Problem Definition,"Historical Overview: Summarizes what actions, ..."
122,Problem Solving Framework,Process Step,Problem Definition,Baseline Metrics (Current State): Quantify the...
124,Problem Solving Framework,Guidance,Problem Definition,Understand KPIs which are meaningful.: Attempt...
126,Problem Solving Framework,Guidance,Problem Definition,What Lens is Problem Defined?: Must be careful...
128,Problem Solving Framework,Guidance,Problem Definition,Stakeholder Investment?: How Invested are stak...
130,Problem Solving Framework,Guidance,Problem Definition,Really Understand Problem Statement: Proceed w...
44,Problem Solving Framework,Process Step,Current State Assessment,NaN
45,Problem Solving Framework,Process Step,Data Collection,"Data collection involves identifying, sourcing..."
132,Problem Solving Framework,Guidance,Data Collection,Challenges from Missing Data: What concessions...
134,Problem Solving Framework,Guidance,Data Collection,"Who is the Steward: Who is the Data Steward, a..."
136,Problem Solving Framework,Guidance,Data Collection,Review Definitions: Review Semantic and Functi...
46,Problem Solving Framework,Process Step,Root Cause Analysis,NaN
47,Problem Solving Framework,Process Step,Research and Exploration,NaN
48,Problem Solving Framework,Process Step,Option Generation,NaN
49,Problem Solving Framework,Process Step,Solution Design,NaN
50,Problem Solving Framework,Process Step,Feasibility Assessment,NaN
51,Problem Solving Framework,Process Step,Prioritization and Decision Making,NaN
52,Problem Solving Framework,Process Step,Implementation Planning,NaN
53,Problem Solving Framework,Process Step,Execution,NaN
54,Problem Solving Framework,Process Step,Testing and Validation,NaN
55,Problem Solving Framework,Process Step,Evaluation,NaN
56,Problem Solving Framework,Process Step,Optimization,NaN
57,Problem Solving Framework,Process Step,Documentation and Knowledge Sharing,NaN
58,Problem Solving Framework,Process Step,Monitoring,Ongoing process of tracking model performance ...
59,Problem Solving Framework,Process Step,Continuous Improvement,NaN
60,Problem Solving Framework,Process Step,"Governance, Risk, and Ethics",NaN

## Manual Test

In [11]:
consolidated_notes = pd.concat([notes_df,manual_object_df.drop('Order',axis=1)])

# Take all Processes from Notes, so we can extract Definitions
process_list = consolidated_notes['Process'].unique().tolist()
process_list.extend(consolidated_notes[consolidated_notes['Categorization']=='Process Step']['Word'].unique().tolist())
process_list = list(set(process_list))

# Extract Definitions to include into Consolidated Notes.
notes_from_def = definition_df[definition_df['Process'].isin(process_list)][['Process','Categorization','Word','Definition']]

# Create a Consolidated notes list (Before Incorporating Definitions).

final_df = pd.concat([
    consolidated_notes,
    notes_from_def])

In [13]:
process_list

['Model Interpretability',
 'Feasibility Assessment',
 'Desired State Metrics',
 'Machine Learning Lifecycle',
 'Option Generation',
 'Monitoring',
 'Optimization',
 'Documentation and Knowledge Sharing',
 'Feature Selection',
 'Implementation Planning',
 'Model Evaluation',
 'Feature Engineering',
 'Solution Design',
 'Behavioural Economics',
 'Data Dictionary',
 'Root Cause Analysis',
 'Data Collection',
 'Testing and Validation',
 'Current State Analysis',
 'Best Linear Unbiased Estimator',
 'Execution',
 'Bias, Fairness, and Ethics',
 'Evaluation',
 'Historical Overview',
 'Documentation',
 'Root Cause Assessment',
 'Continuous Improvement',
 'Validation',
 'Governance, Risk, and Ethics',
 'Hyperparameter Tuning',
 'Training',
 'Notes',
 'Baseline Metrics (Current State)',
 'Current State Assessment',
 'Research and Exploration',
 'Problem Definition',
 'Prioritization and Decision Making',
 'Model Selection',
 'Exploratory Data Analysis',
 'Deployment',
 'Data Preparation',
 'Goal Setting',
 'Problem Solving Framework']

In [6]:
consolidated_notes = pd.concat([notes_df,manual_object_df.drop('Order',axis=1)])

# Take all Processes from Notes, so we can extract Definitions
process_list = consolidated_notes['Process'].unique().tolist()

# Extract Definitions to include into Consolidated Notes.
notes_from_def = definition_df[definition_df['Process'].isin(process_list)][['Process','Categorization','Word','Definition']]

# Create a Consolidated notes list (Before Incorporating Definitions).

final_df = pd.concat([
    consolidated_notes,
    notes_from_def])

# Merge in Sub Processes
word_list = final_df['Word'].unique().tolist()
sub_processes = final_df[(final_df['Process'].isin(word_list))]
#sub_processes = sub_processes.drop(['Categorization'],axis=1).rename(columns={'Word':"Categorization",'Process':'Word','Definition':"Definition"})
# Include Process.

sub_processes['Definition'] = sub_processes['Word'].fillna("") + ": " + sub_processes['Definition'].fillna('')
sub_processes['Word'] = sub_processes['Process']
sub_processes.drop('Process',axis=1,inplace=True)
sub_processes = sub_processes.merge(final_df[['Word','Process']],on='Word',how='left')

final_df = pd.concat([
    final_df,
    sub_processes])

final_df = final_df.merge(definition_df[['Word','Definition']].rename(columns={'Definition':'Definition1'}),on='Word',how='left')
final_df['Definition'] = np.where(final_df['Definition'].notnull(),final_df['Definition'],final_df['Definition1'])
final_df.drop('Definition1',axis=1,inplace=True)
#final_df.reset_index(inplace=True)
#final_df.rename(columns={'index':'default_order'},inplace=True)

# Sorting
# Process - Has to be Alphabetical. Do not actually Care Order.
# Categorization - Based on Manually defined Order, imported from Objects_Manual.
# Words Matter when they are part of a process, generally when not then alphabetically preferred. 

# Merge in Process  Filter
proc_filter = manual_object_df[(manual_object_df['Process']=='Notes')&(manual_object_df['Categorization']=='Filter Order')][['Word','Order']].reset_index(drop=True).rename(columns={'Word':"Categorization",'Order':"proc_order"})
final_df = final_df.merge(proc_filter,on='Categorization',how='left')

# Merge in Word Order.
final_df = final_df.merge(manual_object_df.drop('Categorization',axis=1).rename(columns={'Order':'word_order'}),on=['Process','Word'],how='left')

final_df.sort_values(['Process','word_order','proc_order','Word'],inplace=True)
final_df.drop(['word_order','proc_order'],axis=1,inplace=True)